export const DEFAULT_ECL_CONFIG = [
  {
    tag: 'ecl-grid',
    attributes: {
      columns: 12,
      breakpoint: {
        type: 'select',
        value: '',
        options: [
          { label: 'extra small', value: 'xs' },
          { label: 'small', value: 's' },
          { label: 'medium', value: 'm' },
          { label: 'large', value: 'l' },
          { label: 'extra large', value: 'xl' },
        ],
      },
      row: {
        type: 'boolean',
        value: false,
      },
      container: {
        type: 'boolean',
        value: false,
      },
    },
    inline: false,
    editable: true,
    parent: 'ecl-grid',
  },
  {
    tag: 'ecl-text',
    attributes: {
      'color-mode': {
        type: 'select',
        value: '',
        options: [
          { label: 'blue', value: 'blue' },
          { label: 'green-dark', value: 'green-dark' },
          { label: 'orange', value: 'orange' },
          { label: 'green', value: 'green' },
          { label: 'purple', value: 'purple' },
          { label: 'blue-navy', value: 'blue-navy' },
          { label: 'blue-electric', value: 'blue-electric' },
          { label: 'blue-ocean', value: 'blue-ocean' },
          { label: 'green -lemon', value: 'green-lemon' },
          { label: 'green-pine', value: 'green-pine' },
          { label: 'warm-grey', value: 'warm-grey' },
          { label: 'red-crayola', value: 'red-crayola' },
          { label: 'yellow-gold', value: 'yellow-gold' },
          { label: 'purple-violet', value: 'purple-violet' },
          { label: 'red-tomato', value: 'red-tomato' },
        ],
      },
      'color-mode-typography': '',
      'tag': {
        type: 'select',
        value: 'div',
        options: [
          { label: 'div', value: 'div' },
          { label: 'p', value: 'p' },
          { label: 'h1', value: 'h1' },
          { label: 'h2', value: 'h2' },
          { label: 'h3', value: 'h3' },
          { label: 'h4', value: 'h4' },
          { label: 'h5', value: 'h6' },
          { label: 'span', value: 'span' },
        ],
      },
      'type': {
        type: 'select',
        value: '',
        options: [
          { label: 'display', value: 'display' },
          { label: 'heading', value: 'display' },
          { label: 'paragraph', value: 'paragraph' },
          { label: 'microcopy', value: 'microcoppy' },
        ],
      },
      'font-style': {
        type: 'select',
        value: '',
        options: [
          { label: 'italic', value: 'italic' },
          { label: 'lowercase', value: 'lowercase' },
          { label: 'uppercase', value: 'uppercase' },
          { label: 'capitalize', value: 'capitalize' },
          { label: 'overline', value: 'overline' },
          { label: 'underline', value: 'underline' },
          { label: 'strike', value: 'strike' },
        ],
      },
      'alignment': {
        type: 'select',
        value: '',
        options: [
          { label: 'left', value: 'left' },
          { label: 'right', value: 'right' },
          { label: 'center', value: 'center' },
        ],
      },
      'level': '2',
      'weight': '',
      'enhance': {
        type: 'boolean',
        value: false,
      },
      'enhance-type': {
        type: 'select',
        value: 'enhance',
        options: [
          { label: 'enhance', value: 'enhance' },
          { label: 'strong', value: 'strong' },
          { label: 'light', value: 'light' },
        ],
      },
      'highlighted': {
        type: 'boolean',
        value: false,
      },
      'item-id': '',
      'slot': '',
    },
    inline: true,
    editable: true,
    children: ['ecl-link'],
  },
  {
    tag: 'ecl-spacing',
    attributes: {
      direction: 't',
      breakpoint: '',
      value: 'l',
      outer: {
        type: 'boolean',
        value: true,
      },
      inner: {
        type: 'boolean',
        value: false,
      },
    },
    inline: true,
    editable: true,
  },
  {
    tag: 'ecl-icon',
    attributes: {
      'style-class': '',
      'icon': '',
      'size': {
        type: 'select',
        value: '',
        options: [
          { label: '2xs', value: '2xs' },
          { label: 'xs', value: 'xs' },
          { label: 's', value: 's' },
          { label: 'm', value: 'm' },
          { label: 'l', value: 'l' },
          { label: 'xl', value: 'xl' },
          { label: '2xl', value: '2xl' },
          { label: 'fluid', value: 'fluid' },
        ],
      },
      'color': '',
      'flip': {
        type: 'select',
        value: '',
        options: [
          { label: 'horizontal', value: 'horizontal' },
          { label: 'vertical', value: 'vertical' },
        ],
      },
      'rotate': {
        type: 'select',
        value: '',
        options: [
          { label: '90', value: '90' },
          { label: '180', value: '180' },
          { label: '270', value: '270' },
        ],
      },
      'slot': {
        type: 'select',
        value: '',
        options: [
          { label: 'before', value: 'icon-before' },
          { label: 'after', value: 'icon-after' },
        ],
      },
    },
    inline: true,
    editable: true,
  },
  {
    tag: 'ecl-button',
    attributes: {
      'variant': {
        type: 'select',
        value: '',
        options: [
          { label: 'primary', value: 'primary' },
          { label: 'secondary', value: 'secondary' },
          { label: 'tertiary', value: 'tertiary' },
        ],
      },
      'style-class': '',
      'disabled': {
        type: 'boolean',
        value: false,
      },
      'button-style': {
        type: 'select',
        value: '',
        options: [
          { label: 'highlight', value: 'highlight' },
          { label: 'neutral', value: 'neutral' },
          { label: 'inverted', value: '' },
        ],
      },
      'type': {
        type: 'select',
        value: 'button',
        options: [
          { label: 'button', value: 'button' },
          { label: 'submit', value: 'submit' },
          { label: 'reset', value: 'reset' },
        ],
      },
      'hide-label': {
        type: 'boolean',
        value: false,
      },
      'aria-controls': '',
      'item-id': '',
      'indicator': {
        type: 'boolean',
        value: false,
      },
      'indicator-value': '',
    },
    inline: false,
    editable: true,
    children: ['ecl-icon', 'ecl-indicator'],
  },
  {
    tag: 'ecl-indicator',
    attributes: {
      'no-script': {
        type: 'boolean',
        value: false,
      },
      'style-class': '',
      'sr-label': '',
      'value': '',
    },
  },
  {
    tag: 'ecl-card',
    attributes: {
      'image-alt': '',
      'image': '',
    },
    children: ['ecl-content-block'],
    inline: false,
    editable: true,
  },
  {
    tag: 'ecl-content-block',
    attributes: {
      'has-description': {
        type: 'boolean',
        value: true,
      },
      'has-title': {
        type: 'boolean',
        value: true,
      },
      'has-labels': {
        type: 'boolean',
        value: false,
      },
      'has-links': {
        type: 'boolean',
        value: false,
      },
      'has-secondaryLinks': {
        type: 'boolean',
        value: false,
      },
      'has-lists': {
        type: 'boolean',
        value: false,
      },
      'meta-primary': '',
      'meta-secondary': '',
      'style-class': '',
      'slot': '',
    },
    inline: false,
    editable: true,
    children: ['ecl-label', 'ecl-link', 'ecl-description-list', 'ecl-text'],
  },
  {
    tag: 'ecl-content-item',
    attributes: {
      'color-mode': {
        type: 'select',
        value: '',
        options: [
          { label: 'blue', value: 'blue' },
          { label: 'green-dark', value: 'green-dark' },
          { label: 'orange', value: 'orange' },
          { label: 'green', value: 'green' },
          { label: 'purple', value: 'purple' },
          { label: 'blue-navy', value: 'blue-navy' },
          { label: 'blue-electric', value: 'blue-electric' },
          { label: 'blue-ocean', value: 'blue-ocean' },
          { label: 'green -lemon', value: 'green-lemon' },
          { label: 'green-pine', value: 'green-pine' },
          { label: 'warm-grey', value: 'warm-grey' },
          { label: 'red-crayola', value: 'red-crayola' },
          { label: 'yellow-gold', value: 'yellow-gold' },
          { label: 'purple-violet', value: 'purple-violet' },
          { label: 'red-tomato', value: 'red-tomato' },
        ],
      },
      'image-position': {
        type: 'select',
        value: 'left',
        options: [
          { label: 'left', value: 'left' },
          { label: 'right', value: 'right' },
        ],
      },
      'image-size': {
        type: 'select',
        value: 'medium',
        options: [
          { label: 'small', value: 'small' },
          { label: 'medium', value: 'medium' },
          { label: 'large', value: 'large' },
        ],
      },
      'style-class': '',
    },
    inline: false,
    editable: true,
    children: ['ecl-content-block', 'ecl-picture'],
  },
  {
    tag: 'ecl-tabs',
    attributes: {
      'color-mode': {
        type: 'select',
        value: '',
        options: [
          { label: 'blue', value: 'blue' },
          { label: 'green-dark', value: 'green-dark' },
          { label: 'orange', value: 'orange' },
          { label: 'green', value: 'green' },
          { label: 'purple', value: 'purple' },
          { label: 'blue-navy', value: 'blue-navy' },
          { label: 'blue-electric', value: 'blue-electric' },
          { label: 'blue-ocean', value: 'blue-ocean' },
          { label: 'green -lemon', value: 'green-lemon' },
          { label: 'green-pine', value: 'green-pine' },
          { label: 'warm-grey', value: 'warm-grey' },
          { label: 'red-crayola', value: 'red-crayola' },
          { label: 'yellow-gold', value: 'yellow-gold' },
          { label: 'purple-violet', value: 'purple-violet' },
          { label: 'red-tomato', value: 'red-tomato' },
        ],
      },
      'no-script': {
        type: 'boolean',
        value: false,
      },
      'style-class': '',
      'prev-label': '',
      'next-label': '',
      'more-label': '',
      'without-content': {
        type: 'boolean',
        value: false,
      },
    },
    inline: false,
    editable: true,
    children: ['ecl-tabs-item'],
  },
  {
    tag: 'ecl-tabs-item',
    attributes: {
      'color-mode': {
        type: 'select',
        value: '',
        options: [
          { label: 'blue', value: 'blue' },
          { label: 'green-dark', value: 'green-dark' },
          { label: 'orange', value: 'orange' },
          { label: 'green', value: 'green' },
          { label: 'purple', value: 'purple' },
          { label: 'blue-navy', value: 'blue-navy' },
          { label: 'blue-electric', value: 'blue-electric' },
          { label: 'blue-ocean', value: 'blue-ocean' },
          { label: 'green -lemon', value: 'green-lemon' },
          { label: 'green-pine', value: 'green-pine' },
          { label: 'warm-grey', value: 'warm-grey' },
          { label: 'red-crayola', value: 'red-crayola' },
          { label: 'yellow-gold', value: 'yellow-gold' },
          { label: 'purple-violet', value: 'purple-violet' },
          { label: 'red-tomato', value: 'red-tomato' },
        ],
      },
      'style-class': '',
      'path': '',
      'is-current': {
        type: 'boolean',
        value: false,
      },
      'el-id': '',
    },
    inline: true,
    editable: true,
  },
  {
    tag: 'ecl-navigation-list',
    attributes: {
      'style-class': '',
      'color-mode': {
        type: 'select',
        value: '',
        options: [
          { label: 'blue', value: 'blue' },
          { label: 'green-dark', value: 'green-dark' },
          { label: 'orange', value: 'orange' },
          { label: 'green', value: 'green' },
          { label: 'purple', value: 'purple' },
          { label: 'blue-navy', value: 'blue-navy' },
          { label: 'blue-electric', value: 'blue-electric' },
          { label: 'blue-ocean', value: 'blue-ocean' },
          { label: 'green -lemon', value: 'green-lemon' },
          { label: 'green-pine', value: 'green-pine' },
          { label: 'warm-grey', value: 'warm-grey' },
          { label: 'red-crayola', value: 'red-crayola' },
          { label: 'yellow-gold', value: 'yellow-gold' },
          { label: 'purple-violet', value: 'purple-violet' },
          { label: 'red-tomato', value: 'red-tomato' },
        ],
      },
      'column': '',
    },
    inline: false,
    editable: true,
    children: ['ecl-content-block', 'ecl-navigation-list-item', 'ecl-content-item'],
  },
  {
    tag: 'ecl-navigation-list-item',
    attributes: {
      'style-class': '',
      'color-mode': {
        type: 'select',
        value: '',
        options: [
          { label: 'blue', value: 'blue' },
          { label: 'green-dark', value: 'green-dark' },
          { label: 'orange', value: 'orange' },
          { label: 'green', value: 'green' },
          { label: 'purple', value: 'purple' },
          { label: 'blue-navy', value: 'blue-navy' },
          { label: 'blue-electric', value: 'blue-electric' },
          { label: 'blue-ocean', value: 'blue-ocean' },
          { label: 'green -lemon', value: 'green-lemon' },
          { label: 'green-pine', value: 'green-pine' },
          { label: 'warm-grey', value: 'warm-grey' },
          { label: 'red-crayola', value: 'red-crayola' },
          { label: 'yellow-gold', value: 'yellow-gold' },
          { label: 'purple-violet', value: 'purple-violet' },
          { label: 'red-tomato', value: 'red-tomato' },
        ],
      },
      'border': '',
      'image': '',
      'image-alt': '',
    },
    inline: true,
    editable: true,
    parent: ['ecl-navigation-list'],
    children: ['ecl-content-block'],
  },
  {
    tag: 'ecl-picture',
    attributes: {
      'image': '',
      'img-class': '',
      'image-alt': '',
      'style-class': '',
      'zoom': {
        type: 'boolean',
        value: false,
      },
      'image-anchor': 'center',
      'lazy': {
        type: 'boolean',
        value: false,
      },
      'slot': '',
    },
    inline: false,
    editable: true,
    children: ['source'],
  },
  {
    tag: 'source',
    attributes: {
      media: '',
      type: 'image/jpg',
      srcset: '',
    },
    inline: false,
    editable: true,
  },
  {
    tag: 'ecl-gallery',
    attributes: {
      'no-script': {
        type: 'boolean',
        value: false,
      },
      'counter-label': 'Media files in this gallery',
      'view-all-label': 'View all',
      'counter-separator': 'of',
      'next-label': 'Next',
      'prev-label': 'Previous',
      'close-label': 'Close',
      'full-screen-label': 'View original',
      'share-label': 'Share',
      'visible-items': 8,
      'view-all-expanded-label': 'Back',
      'full-width': {
        type: 'boolean',
        value: false,
      },
      'expandable': {
        type: 'boolean',
        value: true,
      },
      'no-overlay': {
        type: 'boolean',
        value: false,
      },
      'footer-link-path': '',
      'footer-link-label': '',
      'meta': '',
    },
    inline: false,
    editable: true,
  },
  {
    tag: 'ecl-gallery-item',
    attributes: {
      'meta': '',
      'media-share-path': '',
      'media-href': '',
      'image-alt': '',
      'style-class': '',
      'type': {
        type: 'select',
        value: 'image',
        options: [
          { label: 'image', value: 'image' },
          { label: 'video', value: 'video' },
          { label: 'embedded-video', value: 'embedded-video' },
        ],
      },
      'media-iframe-href': '',
    },
    inline: true,
    editable: true,
    parent: 'ecl-gallery',
  },
  {
    tag: 'ecl-modal',
    attributes: {
      'variant': 'default',
      'style-class': '',
      'with-body': {
        type: 'boolean',
        value: true,
      },
      'with-body-fixed': {
        type: 'boolean',
        value: false,
      },
      'with-header': {
        type: 'boolean',
        value: false,
      },
      'no-script': {
        type: 'boolean',
        value: false,
      },
      'with-footer': {
        type: 'boolean',
        value: false,
      },
      'size': {
        type: 'select',
        value: 'l',
        options: [
          { label: 'small', value: 's' },
          { label: 'medium', value: 'm' },
          { label: 'large', value: 'l' },
          { label: 'full', value: 'full' },
        ],
      },
      'toggle-id': '',
      'close-label': '',
      'item-id': '',
    },
    inline: false,
    editable: true,
    children: ['ecl-text'],
  },
  {
    tag: 'ecl-footer',
    attributes: {
      'variant': 'standardised',
      'logo-alt': 'European Union',
      'logo-title': 'European union',
      'logo-lang-code': 'en',
      'logo-link': '',
      'description': 'This site is managed by the Directorate-General for Communication',
      'site-name': 'European Commission website',
    },
    inline: false,
    editable: true,
    children: ['ecl-footer-item', 'ecl-text'],
  },
  {
    tag: 'ecl-footer-item',
    attributes: {
      link: '',
      slot: 'ecl-footer-list-main',
    },
    inline: true,
    editable: true,
    parent: 'ecl-footer',
  },
  {
    tag: 'ecl-mega-menu',
    attributes: {
      'style-class': '',
      'no-script': {
        type: 'boolean',
        value: false,
      },
      'slot': 'menu',
      'close-label': 'Close',
      'back-label': 'Back',
      'menu-id': '',
      'site-name': '',
      'aria-label': '',
    },
    parent: 'ecl-site-header',
    inline: false,
    editable: true,
  },
  {
    tag: 'ecl-menu',
    attributes: {
      'style-class': '',
      'no-script': {
        type: 'boolean',
        value: false,
      },
      'slot': 'menu',
      'close-label': 'Close',
      'back-label': 'Back',
      'menu-link': '/example',
      'menu-title': 'Menu',
      'max-lines': 2,
      'back-label': 'Back',
      'site-name': '',
      'previous-label': '',
      'next-label': '',
    },
    parent: 'ecl-site-header',
    inline: false,
    editable: true,
  },
  {
    tag: 'ecl-list-illustration',
    attributes: {
      'color-mode': {
        type: 'select',
        value: '',
        options: [
          { label: 'blue', value: 'blue' },
          { label: 'green-dark', value: 'green-dark' },
          { label: 'orange', value: 'orange' },
          { label: 'green', value: 'green' },
          { label: 'purple', value: 'purple' },
          { label: 'blue-navy', value: 'blue-navy' },
          { label: 'blue-electric', value: 'blue-electric' },
          { label: 'blue-ocean', value: 'blue-ocean' },
          { label: 'green -lemon', value: 'green-lemon' },
          { label: 'green-pine', value: 'green-pine' },
          { label: 'warm-grey', value: 'warm-grey' },
          { label: 'red-crayola', value: 'red-crayola' },
          { label: 'yellow-gold', value: 'yellow-gold' },
          { label: 'purple-violet', value: 'purple-violet' },
          { label: 'red-tomato', value: 'red-tomato' },
        ],
      },
      'style-class': '',
      'variant': 'image',
      'zebra': {
        type: 'boolean',
        value: false,
      },
      'column': 1,
      'centered': {
        type: 'boolean',
        value: false,
      },
      'item-value': '',
      'media-size': 'm',
      'icon-inline': {
        type: 'boolean',
        value: false,
      },
      'icon-list': {
        type: 'boolean',
        value: false,
      },
      'number-list': {
        type: 'boolean',
        value: false,
      },
      'counter-reset': {
        type: 'boolean',
        value: true,
      },
      'counter-start': 0,
    },
    inline: false,
    editable: true,
  },
  {
    tag: 'ecl-list-illustration-item',
    attributes: {
      'style-class': '',
      'item-title': '',
      'item-link': '',
      'image': '',
      'icon': '',
      'icon-size': {
        type: 'select',
        value: '2xl',
        options: [
          { label: '2xs', value: '2xs' },
          { label: 'xs', value: 'xs' },
          { label: 's', value: 's' },
          { label: 'm', value: 'm' },
          { label: 'l', value: 'l' },
          { label: 'xl', value: 'xl' },
          { label: '2xl', value: '2xl' },
          { label: 'fluid', value: 'fluid' },
        ],
      },
      'image-alt': '',
      'square-image': {
        type: 'boolean',
        value: false,
      },
      'divider': {
        type: 'boolean',
        value: false,
      },
      'media-size': 'm',
      'has-colums': {
        type: 'boolean',
        value: false,
      },
    },
    parent: 'ecl-list-illustration',
    inline: false,
    editable: true,
  },
  {
    tag: 'ecl-mega-menu-item',
    attributes: {
      'style-class': '',
      'path': '',
      'has-children': {
        type: 'boolean',
        value: false,
      },
      'label': '',
      'current': {
        type: 'boolean',
        value: false,
      },
      'slot': '',
    },
    inline: true,
    editable: true,
    parent: ['ecl-mega-menu'],
  },
  {
    tag: 'ecl-mega-menu-subitem',
    attributes: {
      'style-class': '',
      'path': '',
      'label': '',
      'has-children': {
        type: 'boolean',
        value: false,
      },
      'current': {
        type: 'boolean',
        value: false,
      },
    },
    inline: true,
    editable: true,
    parent: 'ecl-mega-menu-item',
  },
  {
    tag: 'ecl-mega-menu-featured-list-item',
    attributes: {
      'style-class': '',
      'path': '',
      'has-description': {
        type: 'boolean',
        value: false,
      },
      'image': '',
      'slot': '',
    },
    inline: true,
    editable: true,
    parent: ['ecl-mega-menu-item', 'ecl-mega-menu-subitem'],
  },
  {
    tag: 'ecl-menu-item',
    attributes: {
      'style-class': '',
      'child': {
        type: 'boolean',
        value: false,
      },
      'link': '',
      'has-children': {
        type: 'boolean',
        value: false,
      },
      'trigger-aria-label': '',
      'current': {
        type: 'boolean',
        value: false,
      },
      'slot': '',
    },
    inline: true,
    editable: true,
    parent: ['ecl-menu'],
  },
  {
    tag: 'ecl-inpage-navigation',
    attributes: {
      'style-class': '',
      'color-mode': {
        type: 'select',
        value: '',
        options: [
          { label: 'blue', value: 'blue' },
          { label: 'green-dark', value: 'green-dark' },
          { label: 'orange', value: 'orange' },
          { label: 'green', value: 'green' },
          { label: 'purple', value: 'purple' },
          { label: 'blue-navy', value: 'blue-navy' },
          { label: 'blue-electric', value: 'blue-electric' },
          { label: 'blue-ocean', value: 'blue-ocean' },
          { label: 'green -lemon', value: 'green-lemon' },
          { label: 'green-pine', value: 'green-pine' },
          { label: 'warm-grey', value: 'warm-grey' },
          { label: 'red-crayola', value: 'red-crayola' },
          { label: 'yellow-gold', value: 'yellow-gold' },
          { label: 'purple-violet', value: 'purple-violet' },
          { label: 'red-tomato', value: 'red-tomato' },
        ],
      },
      'inpage-title': '',
      'inpage-id': '',
      'no-script': {
        type: 'boolean',
        value: false,
      },
    },
    inline: false,
    editable: true,
  },
  {
    tag: 'ecl-inpage-navigation-item',
    attributes: {
      'style-class': '',
      'path': '',
    },
    inline: true,
    editable: true,
    parent: 'ecl-inpage-navigation',
  },
  {
    tag: 'ecl-link',
    attributes: {
      'style-class': '',
      'variant': {
        type: 'select',
        value: '',
        options: [
          { label: 'standalone', value: 'standalone' },
          { label: 'primary', value: 'primary' },
          { label: 'primary-highlight', value: 'primary-highlight' },
          { label: 'primary-neutral', value: 'primary-neutral' },
          { label: 'secondary', value: 'secondary' },
        ],
      },
      'path': '',
      'title-attr': '',
      'external': {
        type: 'boolean',
        value: false,
      },
      'download': {
        type: 'boolean',
        value: false,
      },
      'inverted': {
        type: 'boolean',
        value: false,
      },
      'branded': {
        type: 'boolean',
        value: false,
      },
      'name': '',
      'target': '',
      'slot': '',
      'indicator': {
        type: 'boolean',
        value: false,
      },
      'indicator-value': '',
      'indicator-label': '',
    },
    inline: true,
    editable: true,
    children: ['ecl-icon', 'ecl-indicator'],
  },
  {
    tag: 'ecl-pagination',
    attributes: {
      'style-class': '',
    },
    inline: false,
    editable: true,
  },
  {
    tag: 'ecl-pagination-item',
    attributes: {
      'style-class': '',
      'path': '',
      'aria-label': '',
      'current': {
        type: 'boolean',
        value: false,
      },
      'next': {
        type: 'boolean',
        value: false,
      },
      'previous': {
        type: 'boolean',
        value: false,
      },
    },
    inline: true,
    editable: true,
    parent: 'ecl-pagination',
  },
  {
    tag: 'ecl-breadcrumb',
    attributes: {
      'style-class': '',
      'no-script': {
        type: 'boolean',
        value: false,
      },
      'slot': 'breadcrumb',
    },
    inline: true,
    editable: true,
    parent: 'ecl-page-header',
  },
  {
    tag: 'ecl-breadcrumb-item',
    attributes: {
      'style-class': '',
      'variant': 'negative',
      'path': '',
      'ellipsis': {
        type: 'boolean',
        value: false,
      },
      'button-aria-label': '',
    },
    inline: true,
    editable: true,
    parent: ['ecl-breadcrumb'],
  },
  {
    tag: 'ecl-news-ticker',
    attributes: {
      'style-class': '',
      'items-length': 6,
      'counter-label': 'of',
      'sr-next': 'Next',
      'sr-prev': 'Previous',
      'sr-pause': 'Pause',
      'sr-play': 'Play',
      'no-script': {
        type: 'boolean',
        value: false,
      },
    },
    inline: false,
    editable: true,
  },
  {
    tag: 'ecl-news-ticker-item',
    attributes: {
      'style-class': '',
      'image': '',
      'icon': '',
      'path': '',
    },
    inline: true,
    editable: true,
    parent: 'ecl-news-ticker',
  },
  {
    tag: 'ecl-accordion',
    attributes: {
      'style-class': '',
      'color-mode': {
        type: 'select',
        value: '',
        options: [
          { label: 'blue', value: 'blue' },
          { label: 'green-dark', value: 'green-dark' },
          { label: 'orange', value: 'orange' },
          { label: 'green', value: 'green' },
          { label: 'purple', value: 'purple' },
          { label: 'blue-navy', value: 'blue-navy' },
          { label: 'blue-electric', value: 'blue-electric' },
          { label: 'blue-ocean', value: 'blue-ocean' },
          { label: 'green -lemon', value: 'green-lemon' },
          { label: 'green-pine', value: 'green-pine' },
          { label: 'warm-grey', value: 'warm-grey' },
          { label: 'red-crayola', value: 'red-crayola' },
          { label: 'yellow-gold', value: 'yellow-gold' },
          { label: 'purple-violet', value: 'purple-violet' },
          { label: 'red-tomato', value: 'red-tomato' },
        ],
      },
      'no-script': {
        type: 'boolean',
        value: false,
      },
    },
    inline: false,
    editable: true,
  },
  {
    tag: 'ecl-accordion-item',
    attributes: {
      'style-class': '',
      'item-id': '',
      'label': '',
    },
    inline: true,
    editable: true,
    parent: 'ecl-accordion',
  },
  {
    tag: 'ecl-tag',
    attributes: {
      'style-class': '',
      'variant': {
        type: 'select',
        value: 'link',
        options: [
          { label: 'link', value: 'link' },
          { label: 'removable', value: 'removable' },
        ],
      },
      'external': {
        type: 'boolean',
        value: false,
      },
    },
    inline: true,
    editable: true,
  },
  {
    tag: 'ecl-label',
    attributes: {
      'style-class': '',
      'variant': {
        type: 'select',
        value: '',
        options: [
          { label: 'low', value: 'low' },
          { label: 'medium', value: 'medium' },
          { label: 'high', value: 'high' },
          { label: 'highlight', value: 'hightlight' },
        ],
      },
      'slot': '',
    },
    inline: true,
    editable: true,
  },
  {
    tag: 'ecl-carousel',
    attributes: {
      'style-class': '',
      'color-mode': {
        type: 'select',
        value: '',
        options: [
          { label: 'blue', value: 'blue' },
          { label: 'green-dark', value: 'green-dark' },
          { label: 'orange', value: 'orange' },
          { label: 'green', value: 'green' },
          { label: 'purple', value: 'purple' },
          { label: 'blue-navy', value: 'blue-navy' },
          { label: 'blue-electric', value: 'blue-electric' },
          { label: 'blue-ocean', value: 'blue-ocean' },
          { label: 'green -lemon', value: 'green-lemon' },
          { label: 'green-pine', value: 'green-pine' },
          { label: 'warm-grey', value: 'warm-grey' },
          { label: 'red-crayola', value: 'red-crayola' },
          { label: 'yellow-gold', value: 'yellow-gold' },
          { label: 'purple-violet', value: 'purple-violet' },
          { label: 'red-tomato', value: 'red-tomato' },
        ],
      },
      'carousel-id': '',
      'slides-number': '',
      'no-script': {
        type: 'boolean',
        value: false,
      },
      'size': {
        type: 'select',
        value: 'm',
        options: [
          { label: 'small', value: 's' },
          { label: 'medium', value: 'm' },
          { label: 'large', value: 'l' },
        ],
      },
      'counter-label': 'of',
      'sr-navigation': 'Go to slide %d',
      'sr-previous': 'Prev slides',
      'sr-next': 'Next slides',
      'sr-pause': 'Pause carousel',
      'sr-play': 'Play carousel',
    },
    inline: false,
    editable: true,
  },
  {
    tag: 'ecl-carousel-item',
    attributes: {
      'style-class': '',
      'banner-title': '',
      'centered': {
        type: 'boolean',
        value: false,
      },
      'image': '',
      'cta-link': '',
      'cta-label': '',
      'aria-label': '',
    },
    inline: true,
    editable: true,
    parent: 'ecl-carousel',
  },
  {
    tag: 'ecl-spotlight',
    attributes: {
      'color-mode': {
        type: 'select',
        value: '',
        options: [
          { label: 'blue', value: 'blue' },
          { label: 'green-dark', value: 'green-dark' },
          { label: 'orange', value: 'orange' },
          { label: 'green', value: 'green' },
          { label: 'purple', value: 'purple' },
          { label: 'blue-navy', value: 'blue-navy' },
          { label: 'blue-electric', value: 'blue-electric' },
          { label: 'blue-ocean', value: 'blue-ocean' },
          { label: 'green -lemon', value: 'green-lemon' },
          { label: 'green-pine', value: 'green-pine' },
          { label: 'warm-grey', value: 'warm-grey' },
          { label: 'red-crayola', value: 'red-crayola' },
          { label: 'yellow-gold', value: 'yellow-gold' },
          { label: 'purple-violet', value: 'purple-violet' },
          { label: 'red-tomato', value: 'red-tomato' },
        ],
      },
      'style-class': '',
      'has-anchor': {
        type: 'boolean',
        value: true,
      },
      'path': '',
      'credit': '',
      'image': '',
      'image-alt': '',
      'full-width': {
        type: 'boolean',
        value: false,
      },
      'header': '',
      'font-size': {
        type: 'select',
        value: 'm',
        options: [
          { label: 'medium', value: 'm' },
          { label: 'large', value: 'l' },
        ],
      },
    },
    inline: false,
    editable: true,
  },
  {
    tag: 'ecl-page-information',
    attributes: {
      'style-class': '',
    },
    inline: true,
    editable: true,
  },
  {
    tag: 'ecl-page-header',
    attributes: {
      'style-class': '',
      'header-title': '',
      'image': '',
      'thumbnail': '',
      'with-meta': {
        type: 'boolean',
        value: false,
      },
      'font-size': {
        type: 'select',
        value: 'm',
        options: [
          { label: 'small', value: 's' },
          { label: 'medium', value: 'm' },
        ],
      },
      'variant': {
        type: 'select',
        value: 'default',
        options: [
          { label: 'default', value: 'default' },
          { label: 'news', value: 'news' },
          { label: '50-50', value: '50-50' },
        ],
      },
      'meta': '',
      'thumbnail-alt': '',
      'image-alt': '',
      'description-position': 'top',
      'expandable': {
        type: 'boolean',
        value: false,
      },
      'expandable-content': '',
      'expandable-label': '',
      'expandable-panel-id': '',
    },
    inline: false,
    editable: true,
  },
  {
    tag: 'ecl-fact-figures',
    attributes: {
      'style-class': '',
      'color-mode': {
        type: 'select',
        value: '',
        options: [
          { label: 'blue', value: 'blue' },
          { label: 'green-dark', value: 'green-dark' },
          { label: 'orange', value: 'orange' },
          { label: 'green', value: 'green' },
          { label: 'purple', value: 'purple' },
          { label: 'blue-navy', value: 'blue-navy' },
          { label: 'blue-electric', value: 'blue-electric' },
          { label: 'blue-ocean', value: 'blue-ocean' },
          { label: 'green -lemon', value: 'green-lemon' },
          { label: 'green-pine', value: 'green-pine' },
          { label: 'warm-grey', value: 'warm-grey' },
          { label: 'red-crayola', value: 'red-crayola' },
          { label: 'yellow-gold', value: 'yellow-gold' },
          { label: 'purple-violet', value: 'purple-violet' },
          { label: 'red-tomato', value: 'red-tomato' },
        ],
      },
      'columns': {
        type: 'select',
        value: 3,
        options: [
          { label: '3', value: '3' },
          { label: '4', value: '4' },
        ],
      },
      'display-icons': {
        type: 'boolean',
        value: true,
      },
    },
    inline: false,
    editable: true,
  },
  {
    tag: 'ecl-fact-figures-item',
    attributes: {
      'style-class': '',
      'color-mode': {
        type: 'select',
        value: '',
        options: [
          { label: 'blue', value: 'blue' },
          { label: 'green-dark', value: 'green-dark' },
          { label: 'orange', value: 'orange' },
          { label: 'green', value: 'green' },
          { label: 'purple', value: 'purple' },
          { label: 'blue-navy', value: 'blue-navy' },
          { label: 'blue-electric', value: 'blue-electric' },
          { label: 'blue-ocean', value: 'blue-ocean' },
          { label: 'green -lemon', value: 'green-lemon' },
          { label: 'green-pine', value: 'green-pine' },
          { label: 'warm-grey', value: 'warm-grey' },
          { label: 'red-crayola', value: 'red-crayola' },
          { label: 'yellow-gold', value: 'yellow-gold' },
          { label: 'purple-violet', value: 'purple-violet' },
          { label: 'red-tomato', value: 'red-tomato' },
        ],
      },
      'icon': '',
      'value': '',
      'item-title': '',
      'icon-transform': '',
    },
    inline: true,
    editable: true,
    parent: 'ecl-fact-figures',
  },
  {
    tag: 'ecl-file',
    attributes: {
      'style-class': '',
      'variant': {
        type: 'select',
        value: 'default',
        options: [
          { label: 'default', value: 'default' },
          { label: 'thumbnail', value: 'thumbnail' },
        ],
      },
      'download-label': '',
      'download-link': '',
      'file-title': '',
      'detail-meta': '',
      'language': '',
      'meta': '',
      'image': '',
      'image-alt': '',
      'aria-label': '',
      'no-script': {
        type: 'boolean',
        value: false,
      },
      'labels': '',
      'taxonomies': '',
      'description': ``,
      'taxonomies-label': '',
    },
    inline: false,
    editable: true,
  },
  {
    tag: 'ecl-file-translations',
    attributes: {
      'style-class': '',
      'toggle-label': 'Other languages',
      'translations-total': '',
      'others': {
        type: 'boolean',
        value: true,
      },
      'slot': 'file-translations',
    },
    inline: true,
    editable: true,
    parent: 'ecl-file',
  },
  {
    tag: 'ecl-file-translation-item',
    attributes: {
      'style-class': '',
      'variant': 'default',
      'meta': '',
      'file-title': '',
      'download-link': '',
      'download-label': '',
      'language': '',
    },
    inline: true,
    editable: true,
    parent: 'ecl-file-translations',
  },
  {
    tag: 'ecl-blockquote',
    attributes: {
      'style-class': '',
      'color-mode': {
        type: 'select',
        value: '',
        options: [
          { label: 'blue', value: 'blue' },
          { label: 'green-dark', value: 'green-dark' },
          { label: 'orange', value: 'orange' },
          { label: 'green', value: 'green' },
          { label: 'purple', value: 'purple' },
          { label: 'blue-navy', value: 'blue-navy' },
          { label: 'blue-electric', value: 'blue-electric' },
          { label: 'blue-ocean', value: 'blue-ocean' },
          { label: 'green -lemon', value: 'green-lemon' },
          { label: 'green-pine', value: 'green-pine' },
          { label: 'warm-grey', value: 'warm-grey' },
          { label: 'red-crayola', value: 'red-crayola' },
          { label: 'yellow-gold', value: 'yellow-gold' },
          { label: 'purple-violet', value: 'purple-violet' },
          { label: 'red-tomato', value: 'red-tomato' },
        ],
      },
      'language': 'en',
      'image': '',
      'author': '',
    },
    inline: true,
    editable: true,
  },
  {
    tag: 'ecl-expandable',
    attributes: {
      'style-class': '',
      'is-expanded': {
        type: 'boolean',
        value: false,
      },
      'label-collapsed': 'Expand',
      'label-expanded': 'Collapse',
    },
    inline: false,
    editable: true,
  },
  {
    tag: 'ecl-table',
    attributes: {
      'style-class': '',
      'el-id': '',
      'no-script': {
        type: 'boolean',
        value: false,
      },
      'color-mode': {
        type: 'select',
        value: '',
        options: [
          { label: 'blue', value: 'blue' },
          { label: 'green-dark', value: 'green-dark' },
          { label: 'orange', value: 'orange' },
          { label: 'green', value: 'green' },
          { label: 'purple', value: 'purple' },
          { label: 'blue-navy', value: 'blue-navy' },
          { label: 'blue-electric', value: 'blue-electric' },
          { label: 'blue-ocean', value: 'blue-ocean' },
          { label: 'green -lemon', value: 'green-lemon' },
          { label: 'green-pine', value: 'green-pine' },
          { label: 'warm-grey', value: 'warm-grey' },
          { label: 'red-crayola', value: 'red-crayola' },
          { label: 'yellow-gold', value: 'yellow-gold' },
          { label: 'purple-violet', value: 'purple-violet' },
          { label: 'red-tomato', value: 'red-tomato' },
        ],
      },
      'headers': '',
      'rows': '',
      'caption': '',
      'simple': {
        type: 'boolean',
        value: false,
      },
      'zebra': {
        type: 'boolean',
        value: false,
      },
      'label-sort-ascending': '',
      'label-sort-descending': '',
    },
  },
  {
    tag: 'ecl-media-container',
    attributes: {
      'style-class': '',
      'image': '',
      'alt': '',
      'full-width': {
        type: 'boolean',
        value: false,
      },
      'ratio': '',
      'sources': '',
      'tracks': '',
      'autoplay': {
        type: 'boolean',
        value: false,
      },
      'has-caption': {
        type: 'boolean',
        value: false,
      },
      'image-anchor': 'center',
      'no-script': {
        type: 'boolean',
        value: false,
      },
      'embedded-media': {
        type: 'boolean',
        value: false,
      },
      'sr-play': '',
      'sr-pause': '',
      'sr-video-player': '',
      'sr-video-audio': '',
    },
    inline: false,
    editable: true,
  },
  {
    tag: 'ecl-date-block',
    attributes: {
      'style-class': '',
      'variant': {
        type: 'select',
        value: 'ongoing',
        options: [
          { label: 'ongoing', value: 'ongoing' },
          { label: 'past', value: 'past' },
        ],
      },
      'day': '',
      'month': '',
      'year': '',
      'month-full': '',
      'date-time': '',
    },
    inline: false,
    editable: true,
  },
  {
    tag: 'ecl-spinner',
    attributes: {
      'style-class': '',
      'variant': 'primary',
      'centered': {
        type: 'boolean',
        value: false,
      },
      'visible': {
        type: 'boolean',
        value: true,
      },
      'overlay': {
        type: 'boolean',
        value: false,
      },
    },
    inline: false,
    editable: true,
  },
  {
    tag: 'ecl-popover',
    attributes: {
      'style-class': '',
      'item-id': '',
      'no-script': {
        type: 'boolean',
        value: false,
      },
      'list': {
        type: 'boolean',
        value: true,
      },
      'icon': '',
      'toggle-label': '',
      'indicator': {
        type: 'boolean',
        value: false,
      },
      'indicator-value': '',
      'close': '',
    },
    inline: false,
    editable: true,
  },
  {
    tag: 'ecl-popover-item',
    attributes: {
      'style-class': '',
      'path': '',
      'icon': '',
    },
    inline: true,
    editable: true,
    parent: 'ecl-popover',
  },
  {
    tag: 'ecl-description-list',
    attributes: {
      'no-script': {
        type: 'boolean',
        value: false,
      },
      'style-class': '',
      'color-mode': {
        type: 'select',
        value: '',
        options: [
          { label: 'blue', value: 'blue' },
          { label: 'green-dark', value: 'green-dark' },
          { label: 'orange', value: 'orange' },
          { label: 'green', value: 'green' },
          { label: 'purple', value: 'purple' },
          { label: 'blue-navy', value: 'blue-navy' },
          { label: 'blue-electric', value: 'blue-electric' },
          { label: 'blue-ocean', value: 'blue-ocean' },
          { label: 'green -lemon', value: 'green-lemon' },
          { label: 'green-pine', value: 'green-pine' },
          { label: 'warm-grey', value: 'warm-grey' },
          { label: 'red-crayola', value: 'red-crayola' },
          { label: 'yellow-gold', value: 'yellow-gold' },
          { label: 'purple-violet', value: 'purple-violet' },
          { label: 'red-tomato', value: 'red-tomato' },
        ],
      },
      'variant': 'vertical',
      'visible-items': '',
      'more-label': '',
      'slot': '',
    },
    inline: false,
    editable: true,
  },
  {
    tag: 'ecl-description-list-term',
    attributes: {
      'style-class': '',
      'variant': 'vertical',
    },
    inline: true,
    editable: true,
    parent: 'ecl-description-list',
  },
  {
    tag: 'ecl-description-list-definition',
    attributes: {
      'style-class': '',
      'items': '',
      'type': {
        type: 'select',
        value: 'link',
        options: [
          { label: 'link', value: 'link' },
          { label: 'link-inline', value: 'link-inline' },
          { label: 'taxonomy', value: 'taxonomy' },
          { label: 'tag', value: 'tag' },
        ],
      },
    },
    inline: true,
    editable: true,
    parent: 'ecl-description-list',
  },
  {
    tag: 'ecl-banner',
    attributes: {
      'no-script': {
        type: 'boolean',
        value: false,
      },
      'style-class': '',
      'color-mode': {
        type: 'select',
        value: '',
        options: [
          { label: 'blue', value: 'blue' },
          { label: 'green-dark', value: 'green-dark' },
          { label: 'orange', value: 'orange' },
          { label: 'green', value: 'green' },
          { label: 'purple', value: 'purple' },
          { label: 'blue-navy', value: 'blue-navy' },
          { label: 'blue-electric', value: 'blue-electric' },
          { label: 'blue-ocean', value: 'blue-ocean' },
          { label: 'green -lemon', value: 'green-lemon' },
          { label: 'green-pine', value: 'green-pine' },
          { label: 'warm-grey', value: 'warm-grey' },
          { label: 'red-crayola', value: 'red-crayola' },
          { label: 'yellow-gold', value: 'yellow-gold' },
          { label: 'purple-violet', value: 'purple-violet' },
          { label: 'red-tomato', value: 'red-tomato' },
        ],
      },
      'external': {
        type: 'boolean',
        value: false,
      },
      'size': {
        type: 'select',
        value: 'm',
        options: [
          { label: 'extra small', value: 'xs' },
          { label: 'small', value: 's' },
          { label: 'medium', value: 'm' },
          { label: 'large', value: 'l' },
        ],
      },
      'full-width': {
        type: 'boolean',
        value: false,
      },
      'banner-title': '',
      'banner-title-link': '',
      'description-link': '',
      'box-background': '',
      'horizontal': {
        type: 'select',
        value: '',
        options: [
          { label: 'left', value: 'left' },
          { label: 'center', value: 'center' },
          { label: 'right', value: 'right' },
        ],
      },
      'vertical': {
        type: 'select',
        value: '',
        options: [
          { label: 'top', value: 'top' },
          { label: 'center', value: 'center' },
          { label: 'bottom', value: 'bottom' },
        ],
      },
      'image': '',
      'cta-label': '',
      'cta-link': '',
      'credit': '',
      'font-color': {
        type: 'select',
        value: 'dark',
        options: [
          { label: 'light', value: 'light' },
          { label: 'dark', value: 'dark' },
        ],
      },
      'image-alt': '',
      'sr-play': '',
      'sr-pause': '',
    },
    inline: false,
    editable: true,
  },
  {
    tag: 'ecl-notification',
    attributes: {
      'style-class': '',
      'variant': {
        type: 'select',
        value: '',
        options: [
          { label: 'information', value: 'information' },
          { label: 'success', value: 'success' },
          { label: 'warning', value: 'warning' },
          { label: 'error', value: 'error' },
        ],
      },
      'message-title': '',
      'close-label': '',
      'slot': '',
    },
    inline: false,
    editable: true,
  },
  {
    tag: 'ecl-form-group',
    attributes: {
      'style-class': '',
      'label': '',
      'required': {
        type: 'boolean',
        value: true,
      },
      'optional-text': '',
      'helper-text': '',
      'invalid': {
        type: 'boolean',
        value: false,
      },
      'disabled': {
        type: 'boolean',
        value: false,
      },
      'invalid-text': '',
    },
    inline: false,
    editable: true,
  },
  {
    tag: 'ecl-input',
    attributes: {
      'style-class': '',
      'type': {
        type: 'select',
        value: 'text',
        options: [
          { label: 'text', value: 'text' },
          { label: 'search', value: 'search' },
          { label: 'radio', value: 'radio' },
          { label: 'checkbox', value: 'checkbox' },
        ],
      },
      'width': {
        type: 'select',
        value: 'm',
        options: [
          { label: 'small', value: 's' },
          { label: 'medium', value: 'm' },
          { label: 'large', value: 'l' },
        ],
      },
      'disabled': {
        type: 'boolean',
        value: false,
      },
      'required': {
        type: 'boolean',
        value: false,
      },
      'invalid': {
        type: 'boolean',
        value: false,
      },
      'input-id': '',
      'name': '',
      'max': '',
      'min': '',
      'label': '',
      'placeholder': '',
      'default-value': '',
      'step': 1,
      'no-script': {
        type: 'boolean',
        value: false,
      },
      'multiple': {
        type: 'boolean',
        value: false,
      },
      'button-replace-label': 'Replace file',
      'button-choose-label': 'Choose file',
    },
    inline: true,
    editable: true,
    parent: 'ecl-form-group',
  },
  {
    tag: 'ecl-select',
    attributes: {
      'style-class': '',
      'required': {
        type: 'boolean',
        value: true,
      },
      'disabled': {
        type: 'boolean',
        value: false,
      },
      'invalid': {
        type: 'boolean',
        value: false,
      },
      'width': {
        type: 'select',
        value: 'm',
        options: [
          { label: 'small', value: 's' },
          { label: 'medium', value: 'm' },
          { label: 'large', value: 'l' },
        ],
      },
      'no-script': {
        type: 'boolean',
        value: false,
      },
      'label': '',
      'select-id': '',
      'helper-text': ``,
      'required-text': '*',
      'invalid-text': '',
      'invalid-icon': '',
      'optional-text': '',
      'multiple': {
        type: 'boolean',
        value: false,
      },
      'multiple-placeholder': '',
      'multiple-search-no-results-text': '',
      'multiple-all-text': '',
      'multiple-clear-all-text': '',
      'multiple-close-text': '',
      'multiple-search-text': '',
    },
    inline: true,
    editable: true,
    parent: 'ecl-form-group',
  },
  {
    tag: 'ecl-rating-field',
    attributes: {
      'style-class': '',
      'disabled': {
        type: 'boolean',
        value: false,
      },
      'required': {
        type: 'boolean',
        value: true,
      },
    },
    inline: true,
    editable: true,
    parent: 'ecl-form-group',
  },
  {
    tag: 'ecl-rating-star',
    attributes: {
      'style-class': '',
      'value': '',
      'item-id': '',
      'label': 'star',
      'disabled': {
        type: 'boolean',
        value: false,
      },
      'required': {
        type: 'boolean',
        value: true,
      },
    },
    inline: true,
    editable: true,
    parent: 'ecl-rating-field',
  },
  {
    tag: 'ecl-textarea',
    attributes: {
      'style-class': '',
      'required': {
        type: 'boolean',
        value: false,
      },
      'invalid': {
        type: 'boolean',
        value: false,
      },
      'disabled': {
        type: 'boolean',
        value: false,
      },
      'name': '',
      'width': {
        type: 'select',
        value: 'm',
        options: [
          { label: 'small', value: 's' },
          { label: 'medium', value: 'm' },
          { label: 'large', value: 'l' },
        ],
      },
      'textarea-id': '',
    },
    inline: true,
    editable: true,
    parent: 'ecl-form-group',
  },
  {
    tag: 'ecl-featured-item',
    attributes: {
      'style-class': '',
      'el-id': '',
      'variant': {
        type: 'select',
        value: '',
        options: [
          { label: 'default', value: '' },
          { label: 'highlight', value: 'highlight' },
        ],
      },
      'position': {
        type: 'select',
        value: 'left',
        options: [
          { label: 'left', value: 'left' },
          { label: 'right', value: 'right' },
        ],
      },
      'item-title': '',
      'image': '',
      'media-caption': '',
      'media-anchor': '',
    },
    inline: false,
    editable: true,
    children: ['ecl-button', 'ecl-link', 'ecl-icon', 'ecl-text'],
  },
  {
    tag: 'ecl-site-header',
    attributes: {
      'style-class': '',
      'no-script': {
        type: 'boolean',
        value: false,
      },
      'login-block': {
        type: 'boolean',
        value: true,
      },
      'language-block': {
        type: 'boolean',
        value: true,
      },
      'search-block': {
        type: 'boolean',
        value: true,
      },
      'search-text': '',
      'logo-size': {
        type: 'select',
        value: 'l',
        options: [
          { label: 'small', value: 's' },
          { label: 'medium', value: 'm' },
          { label: 'large', value: 'l' },
        ],
      },
      'site-name-mobile-only': {
        type: 'boolean',
        value: false,
      },
      'search-placeholder': '',
      'language': '',
      'lang-code': '',
      'login-text': '',
      'logged': {
        type: 'boolean',
        value: false,
      },
      'logged-in-text': '',
      'logout-text': '',
      'logout-link': '',
      'banner-top': '',
      'banner-top-link': '',
      'eu-label': '',
      'non-eu-label': '',
      'language-title': '',
      'login-link': '',
      'language-id': '',
      'logo-alt': '',
      'logo-title': '',
      'language-aria-label': '',
    },
    inline: false,
    editable: true,
  },
  {
    tag: 'ecl-language-item',
    attributes: {
      'style-class': '',
      'slot': '',
      'path': '',
      'lang-code': '',
      'language': '',
    },
    inline: true,
    editable: true,
    parent: 'ecl-site-header',
  },
  {
    tag: 'ecl-timeline',
    attributes: {
      'style-class': '',
      'no-script': {
        type: 'boolean',
        value: false,
      },
    },
    inline: false,
    editable: true,
  },
  {
    tag: 'ecl-timeline-item',
    attributes: {
      'style-class': '',
      'item-id': '',
      'label': '',
      'type': {
        type: 'select',
        value: 'default',
        options: [
          { label: 'default', value: '' },
          { label: 'toggle', value: 'toggle' },
        ],
      },
    },
    inline: true,
    editable: true,
    parent: 'ecl-timeline',
  },
];
