/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface EclAccordion {
        "eclScript": boolean;
        "styleClass": string;
        "theme": string;
        "withUtils": boolean;
    }
    interface EclAccordionItem {
        "expanded": boolean;
        "label": string;
        "styleClass": string;
        "theme": string;
    }
    interface EclBanner {
        "bannerTitle": string;
        "centered": boolean;
        "credit": string;
        "ctaLabel": string;
        "ctaLink": string;
        "external": boolean;
        "fullWidth": boolean;
        "image": string;
        "size": string;
        "styleClass": string;
        "theme": string;
        "variant": string;
    }
    interface EclBlockquote {
        "author": string;
        "image": string;
        "imageAlt": string;
        "styleClass": string;
        "theme": string;
    }
    interface EclBreadcrumb {
        "eclScript": boolean;
        "minItemsRight": number;
        "styleClass": string;
        "theme": string;
        "variant": string;
    }
    interface EclBreadcrumbItem {
        "buttonAriaLabel": string;
        "currentPage": boolean;
        "ellipsis": boolean;
        "path": string;
        "styleClass": string;
        "theme": string;
        "variant": string;
    }
    interface EclButton {
        "styleClass": string;
        "theme": string;
        "type": string;
        "variant": string;
    }
    interface EclCarousel {
        "carouselId": string;
        "counterLabel": string;
        "eclScript": boolean;
        "slidesNumber": number;
        "srNavigation": string;
        "srNext": string;
        "srPause": string;
        "srPlay": string;
        "srPrevious": string;
        "styleClass": string;
        "theme": string;
    }
    interface EclCarouselItem {
        "ariaLabel": string;
        "bannerTitle": string;
        "bannerVariant": string;
        "centered": boolean;
        "ctaLabel": string;
        "ctaLink": string;
        "image": string;
        "size": string;
        "styleClass": string;
        "theme": string;
    }
    interface EclCategoryFilter {
        "eclScript": boolean;
        "styleClass": string;
        "theme": string;
    }
    interface EclCategoryFilterItem {
        "label": string;
        "level": number;
        "path": string;
        "styleClass": string;
        "subItems": boolean;
        "theme": string;
    }
    interface EclContentBlock {
        "hasDescription": boolean;
        "hasLabels": boolean;
        "hasLinks": boolean;
        "hasLists": boolean;
        "hasSecondaryLinks": boolean;
        "hasTitle": boolean;
        "metaPrimary": string;
        "metaSecondary": string;
        "styleClass": string;
        "theme": string;
    }
    interface EclDateBlock {
        "dateTime": string;
        "day": string;
        "month": string;
        "monthFull": string;
        "styleClass": string;
        "theme": string;
        "variant": string;
        "year": string;
    }
    interface EclDatepicker {
        "defaultValue": string;
        "disabled": boolean;
        "inputId": string;
        "invalid": boolean;
        "name": string;
        "placeholder": string;
        "required": boolean;
        "styleClass": string;
        "theme": string;
        "type": string;
    }
    interface EclDescriptionList {
        "styleClass": string;
        "theme": string;
        "variant": string;
    }
    interface EclDescriptionListDefinition {
        "items": string;
        "styleClass": string;
        "theme": string;
        "type": string;
    }
    interface EclDescriptionListTerm {
        "styleClass": string;
        "theme": string;
    }
    interface EclExpandable {
        "eclScript": boolean;
        "isExpanded": boolean;
        "labelCollapsed": string;
        "labelExpanded": string;
        "styleClass": string;
        "theme": string;
        "withUtils": boolean;
    }
    interface EclFactFigures {
        "columns": number;
        "displayIcons": boolean;
        "styleClass": string;
        "theme": string;
        "withUtils": boolean;
    }
    interface EclFactFiguresItem {
        "icon": string;
        "iconTransform": string;
        "itemTitle": string;
        "styleClass": string;
        "theme": string;
        "value": string;
    }
    interface EclFeaturedItem {
        "defaultContainerClass": string;
        "eclScript": boolean;
        "image": string;
        "itemTitle": string;
        "mediaCaption": string;
        "position": string;
        "styleClass": string;
        "theme": string;
        "variant": string;
        "withUtils": boolean;
    }
    interface EclFile {
        "ariaLabel": string;
        "detailMeta": string;
        "downloadLabel": string;
        "downloadLink": string;
        "eclScript": boolean;
        "fileTitle": string;
        "image": string;
        "imageAlt": string;
        "labels": string;
        "language": string;
        "meta": string;
        "styleClass": string;
        "taxonomies": string;
        "taxonomiesLabel": string;
        "theme": string;
        "variant": string;
    }
    interface EclFileTranslations {
        "others": boolean;
        "styleClass": string;
        "theme": string;
        "toggleLabel": string;
    }
    interface EclFileTranslationsItem {
        "downloadLabel": string;
        "downloadLink": string;
        "fileTitle": string;
        "language": string;
        "meta": string;
        "styleClass": string;
        "theme": string;
        "variant": string;
    }
    interface EclFormGroup {
        "helperId": string;
        "helperText": string;
        "invalid": boolean;
        "invalidIcon": string;
        "invalidText": string;
        "label": string;
        "labelClass": string;
        "name": string;
        "optionalText": string;
        "required": boolean;
        "requiredText": string;
        "styleClass": string;
        "theme": string;
    }
    interface EclGallery {
        "closeLabel": string;
        "counterLabel": string;
        "counterSeparator": string;
        "description": string;
        "downloadLabel": string;
        "eclScript": boolean;
        "footerLinkLabel": string;
        "footerLinkPath": string;
        "meta": string;
        "nextLabel": string;
        "prevLabel": string;
        "shareLabel": string;
        "slidesNumber": number;
        "styleClass": string;
        "theme": string;
        "viewAllLabel": string;
    }
    interface EclGalleryItem {
        "icon": string;
        "imageAlt": string;
        "mediaHref": string;
        "mediaIframeHref": string;
        "mediaSharePath": string;
        "meta": string;
        "styleClass": string;
        "theme": string;
        "type": string;
    }
    interface EclHeroBanner {
        "bannerTitle": string;
        "centered": boolean;
        "credit": string;
        "ctaLabel": string;
        "ctaLink": string;
        "external": boolean;
        "fullWidth": boolean;
        "image": string;
        "styleClass": string;
        "theme": string;
        "variant": string;
    }
    interface EclIcon {
        "color": string;
        "icon": string;
        "path": string;
        "size": string;
        "sprite": string;
        "styleClass": string;
        "theme": string;
        "transform": string;
    }
    interface EclInpageNavigation {
        "eclScript": boolean;
        "inpageId": string;
        "inpageTitle": string;
        "styleClass": string;
        "theme": string;
        "withUtils": boolean;
    }
    interface EclInpageNavigationItem {
        "path": string;
        "styleClass": string;
        "theme": string;
    }
    interface EclInput {
        "buttonChooseLabel": string;
        "buttonReplaceLabel": string;
        "defaultValue": string;
        "disabled": boolean;
        "eclScript": boolean;
        "helperId": string;
        "helperText": string;
        "inputClass": string;
        "inputId": string;
        "invalid": boolean;
        "label": string;
        "max": number;
        "min": number;
        "multiple": boolean;
        "name": string;
        "placeholder": string;
        "required": boolean;
        "step": number;
        "styleClass": string;
        "theme": string;
        "type": string;
        "valueLabel": string;
        "width": string;
        "withUtils": boolean;
    }
    interface EclLabel {
        "styleClass": string;
        "theme": string;
        "variant": string;
    }
    interface EclLanguageItem {
        "active": boolean;
        "langCode": string;
        "language": string;
        "path": string;
        "styleClass": string;
        "theme": string;
    }
    interface EclLink {
        "external": boolean;
        "name": string;
        "path": string;
        "styleClass": string;
        "theme": string;
        "titleAttr": string;
        "variant": string;
    }
    interface EclMediaContainer {
        "alt": string;
        "description": string;
        "eclScript": boolean;
        "embeddedMedia": boolean;
        "fullWidth": boolean;
        "image": string;
        "ratio": string;
        "sources": string;
        "styleClass": string;
        "theme": string;
        "tracks": string;
        "withUtils": boolean;
    }
    interface EclMessage {
        "closeLabel": string;
        "eclScript": boolean;
        "messageTitle": string;
        "styleClass": string;
        "theme": string;
        "variant": string;
    }
    interface EclNewsTicker {
        "counterLabel": string;
        "eclScript": boolean;
        "srNext": string;
        "srPause": string;
        "srPrev": string;
        "styleClass": string;
        "theme": string;
    }
    interface EclNewsTickerItem {
        "path": string;
        "styleClass": string;
        "theme": string;
    }
    interface EclPageBanner {
        "bannerTitle": string;
        "centered": boolean;
        "credit": string;
        "ctaLabel": string;
        "ctaLink": string;
        "external": boolean;
        "fullWidth": boolean;
        "image": string;
        "styleClass": string;
        "theme": string;
        "variant": string;
    }
    interface EclPageHeader {
        "headerTitle": string;
        "image": string;
        "meta": string;
        "overlay": string;
        "styleClass": string;
        "theme": string;
        "thumbnail": string;
        "thumbnailAlt": string;
        "variant": string;
    }
    interface EclPopover {
        "eclScript": boolean;
        "icon": string;
        "iconSize": string;
        "iconSprite": string;
        "itemId": string;
        "list": boolean;
        "styleClass": string;
        "theme": string;
        "toggleLabel": string;
    }
    interface EclPopoverItem {
        "icon": string;
        "iconSize": string;
        "iconSprite": string;
        "path": string;
        "styleClass": string;
        "theme": string;
    }
    interface EclRatingField {
        "disabled": boolean;
        "required": boolean;
        "styleClass": string;
        "theme": string;
    }
    interface EclRatingStar {
        "checked": boolean;
        "disabled": boolean;
        "icon": string;
        "iconFilled": string;
        "itemId": string;
        "label": string;
        "name": string;
        "required": boolean;
        "styleClass": string;
        "theme": string;
        "value": string;
    }
    interface EclSearchForm {
        "buttonAriaLabel": string;
        "buttonLabel": string;
        "disabled": boolean;
        "helperId": string;
        "helperText": string;
        "inputId": string;
        "invalid": boolean;
        "invalidText": string;
        "label": string;
        "name": string;
        "placeholder": string;
        "required": boolean;
        "styleClass": string;
        "theme": string;
        "type": string;
        "width": string;
    }
    interface EclSelect {
        "disabled": boolean;
        "eclScript": boolean;
        "invalid": boolean;
        "multiple": boolean;
        "multipleAllText": string;
        "multipleClearAllText": string;
        "multipleCloseText": string;
        "multiplePlaceholder": string;
        "multipleSearchNoResultsText": string;
        "multipleSearchText": string;
        "name": string;
        "required": boolean;
        "selectId": string;
        "styleClass": string;
        "theme": string;
        "width": string;
    }
    interface EclSiteHeader {
        "closeLabel": string;
        "eclScript": boolean;
        "euLabel": string;
        "langCode": string;
        "language": string;
        "languageAriaLabel": string;
        "languageBlock": boolean;
        "languageId": string;
        "languageTitle": string;
        "loginBlock": boolean;
        "loginLink": string;
        "loginText": string;
        "logoAlt": string;
        "logoTitle": string;
        "nonEuLabel": string;
        "searchBlock": boolean;
        "searchPlaceholder": string;
        "searchText": string;
        "styleClass": string;
        "theme": string;
    }
    interface EclSocialMediaShare {
        "description": string;
        "styleClass": string;
        "theme": string;
        "variant": string;
    }
    interface EclSocialMediaShareItem {
        "icon": string;
        "sharePath": string;
        "styleClass": string;
        "theme": string;
    }
    interface EclSpinner {
        "centered": boolean;
        "overlay": boolean;
        "size": string;
        "styleClass": string;
        "theme": string;
        "variant": string;
        "visible": boolean;
    }
    interface EclTag {
        "external": boolean;
        "styleClass": string;
        "theme": string;
        "variant": string;
    }
    interface EclTextarea {
        "disabled": boolean;
        "invalid": boolean;
        "name": string;
        "placeholder": string;
        "required": boolean;
        "rows": number;
        "styleClass": string;
        "textareaId": string;
        "theme": string;
        "width": string;
    }
    interface EclTimeline {
        "eclScript": boolean;
        "styleClass": string;
        "theme": string;
    }
    interface EclTimelineItem {
        "itemTitle": string;
        "label": string;
        "styleClass": string;
        "theme": string;
        "type": string;
    }
}
declare global {
    interface HTMLEclAccordionElement extends Components.EclAccordion, HTMLStencilElement {
    }
    var HTMLEclAccordionElement: {
        prototype: HTMLEclAccordionElement;
        new (): HTMLEclAccordionElement;
    };
    interface HTMLEclAccordionItemElement extends Components.EclAccordionItem, HTMLStencilElement {
    }
    var HTMLEclAccordionItemElement: {
        prototype: HTMLEclAccordionItemElement;
        new (): HTMLEclAccordionItemElement;
    };
    interface HTMLEclBannerElement extends Components.EclBanner, HTMLStencilElement {
    }
    var HTMLEclBannerElement: {
        prototype: HTMLEclBannerElement;
        new (): HTMLEclBannerElement;
    };
    interface HTMLEclBlockquoteElement extends Components.EclBlockquote, HTMLStencilElement {
    }
    var HTMLEclBlockquoteElement: {
        prototype: HTMLEclBlockquoteElement;
        new (): HTMLEclBlockquoteElement;
    };
    interface HTMLEclBreadcrumbElement extends Components.EclBreadcrumb, HTMLStencilElement {
    }
    var HTMLEclBreadcrumbElement: {
        prototype: HTMLEclBreadcrumbElement;
        new (): HTMLEclBreadcrumbElement;
    };
    interface HTMLEclBreadcrumbItemElement extends Components.EclBreadcrumbItem, HTMLStencilElement {
    }
    var HTMLEclBreadcrumbItemElement: {
        prototype: HTMLEclBreadcrumbItemElement;
        new (): HTMLEclBreadcrumbItemElement;
    };
    interface HTMLEclButtonElement extends Components.EclButton, HTMLStencilElement {
    }
    var HTMLEclButtonElement: {
        prototype: HTMLEclButtonElement;
        new (): HTMLEclButtonElement;
    };
    interface HTMLEclCarouselElement extends Components.EclCarousel, HTMLStencilElement {
    }
    var HTMLEclCarouselElement: {
        prototype: HTMLEclCarouselElement;
        new (): HTMLEclCarouselElement;
    };
    interface HTMLEclCarouselItemElement extends Components.EclCarouselItem, HTMLStencilElement {
    }
    var HTMLEclCarouselItemElement: {
        prototype: HTMLEclCarouselItemElement;
        new (): HTMLEclCarouselItemElement;
    };
    interface HTMLEclCategoryFilterElement extends Components.EclCategoryFilter, HTMLStencilElement {
    }
    var HTMLEclCategoryFilterElement: {
        prototype: HTMLEclCategoryFilterElement;
        new (): HTMLEclCategoryFilterElement;
    };
    interface HTMLEclCategoryFilterItemElement extends Components.EclCategoryFilterItem, HTMLStencilElement {
    }
    var HTMLEclCategoryFilterItemElement: {
        prototype: HTMLEclCategoryFilterItemElement;
        new (): HTMLEclCategoryFilterItemElement;
    };
    interface HTMLEclContentBlockElement extends Components.EclContentBlock, HTMLStencilElement {
    }
    var HTMLEclContentBlockElement: {
        prototype: HTMLEclContentBlockElement;
        new (): HTMLEclContentBlockElement;
    };
    interface HTMLEclDateBlockElement extends Components.EclDateBlock, HTMLStencilElement {
    }
    var HTMLEclDateBlockElement: {
        prototype: HTMLEclDateBlockElement;
        new (): HTMLEclDateBlockElement;
    };
    interface HTMLEclDatepickerElement extends Components.EclDatepicker, HTMLStencilElement {
    }
    var HTMLEclDatepickerElement: {
        prototype: HTMLEclDatepickerElement;
        new (): HTMLEclDatepickerElement;
    };
    interface HTMLEclDescriptionListElement extends Components.EclDescriptionList, HTMLStencilElement {
    }
    var HTMLEclDescriptionListElement: {
        prototype: HTMLEclDescriptionListElement;
        new (): HTMLEclDescriptionListElement;
    };
    interface HTMLEclDescriptionListDefinitionElement extends Components.EclDescriptionListDefinition, HTMLStencilElement {
    }
    var HTMLEclDescriptionListDefinitionElement: {
        prototype: HTMLEclDescriptionListDefinitionElement;
        new (): HTMLEclDescriptionListDefinitionElement;
    };
    interface HTMLEclDescriptionListTermElement extends Components.EclDescriptionListTerm, HTMLStencilElement {
    }
    var HTMLEclDescriptionListTermElement: {
        prototype: HTMLEclDescriptionListTermElement;
        new (): HTMLEclDescriptionListTermElement;
    };
    interface HTMLEclExpandableElement extends Components.EclExpandable, HTMLStencilElement {
    }
    var HTMLEclExpandableElement: {
        prototype: HTMLEclExpandableElement;
        new (): HTMLEclExpandableElement;
    };
    interface HTMLEclFactFiguresElement extends Components.EclFactFigures, HTMLStencilElement {
    }
    var HTMLEclFactFiguresElement: {
        prototype: HTMLEclFactFiguresElement;
        new (): HTMLEclFactFiguresElement;
    };
    interface HTMLEclFactFiguresItemElement extends Components.EclFactFiguresItem, HTMLStencilElement {
    }
    var HTMLEclFactFiguresItemElement: {
        prototype: HTMLEclFactFiguresItemElement;
        new (): HTMLEclFactFiguresItemElement;
    };
    interface HTMLEclFeaturedItemElement extends Components.EclFeaturedItem, HTMLStencilElement {
    }
    var HTMLEclFeaturedItemElement: {
        prototype: HTMLEclFeaturedItemElement;
        new (): HTMLEclFeaturedItemElement;
    };
    interface HTMLEclFileElement extends Components.EclFile, HTMLStencilElement {
    }
    var HTMLEclFileElement: {
        prototype: HTMLEclFileElement;
        new (): HTMLEclFileElement;
    };
    interface HTMLEclFileTranslationsElement extends Components.EclFileTranslations, HTMLStencilElement {
    }
    var HTMLEclFileTranslationsElement: {
        prototype: HTMLEclFileTranslationsElement;
        new (): HTMLEclFileTranslationsElement;
    };
    interface HTMLEclFileTranslationsItemElement extends Components.EclFileTranslationsItem, HTMLStencilElement {
    }
    var HTMLEclFileTranslationsItemElement: {
        prototype: HTMLEclFileTranslationsItemElement;
        new (): HTMLEclFileTranslationsItemElement;
    };
    interface HTMLEclFormGroupElement extends Components.EclFormGroup, HTMLStencilElement {
    }
    var HTMLEclFormGroupElement: {
        prototype: HTMLEclFormGroupElement;
        new (): HTMLEclFormGroupElement;
    };
    interface HTMLEclGalleryElement extends Components.EclGallery, HTMLStencilElement {
    }
    var HTMLEclGalleryElement: {
        prototype: HTMLEclGalleryElement;
        new (): HTMLEclGalleryElement;
    };
    interface HTMLEclGalleryItemElement extends Components.EclGalleryItem, HTMLStencilElement {
    }
    var HTMLEclGalleryItemElement: {
        prototype: HTMLEclGalleryItemElement;
        new (): HTMLEclGalleryItemElement;
    };
    interface HTMLEclHeroBannerElement extends Components.EclHeroBanner, HTMLStencilElement {
    }
    var HTMLEclHeroBannerElement: {
        prototype: HTMLEclHeroBannerElement;
        new (): HTMLEclHeroBannerElement;
    };
    interface HTMLEclIconElement extends Components.EclIcon, HTMLStencilElement {
    }
    var HTMLEclIconElement: {
        prototype: HTMLEclIconElement;
        new (): HTMLEclIconElement;
    };
    interface HTMLEclInpageNavigationElement extends Components.EclInpageNavigation, HTMLStencilElement {
    }
    var HTMLEclInpageNavigationElement: {
        prototype: HTMLEclInpageNavigationElement;
        new (): HTMLEclInpageNavigationElement;
    };
    interface HTMLEclInpageNavigationItemElement extends Components.EclInpageNavigationItem, HTMLStencilElement {
    }
    var HTMLEclInpageNavigationItemElement: {
        prototype: HTMLEclInpageNavigationItemElement;
        new (): HTMLEclInpageNavigationItemElement;
    };
    interface HTMLEclInputElement extends Components.EclInput, HTMLStencilElement {
    }
    var HTMLEclInputElement: {
        prototype: HTMLEclInputElement;
        new (): HTMLEclInputElement;
    };
    interface HTMLEclLabelElement extends Components.EclLabel, HTMLStencilElement {
    }
    var HTMLEclLabelElement: {
        prototype: HTMLEclLabelElement;
        new (): HTMLEclLabelElement;
    };
    interface HTMLEclLanguageItemElement extends Components.EclLanguageItem, HTMLStencilElement {
    }
    var HTMLEclLanguageItemElement: {
        prototype: HTMLEclLanguageItemElement;
        new (): HTMLEclLanguageItemElement;
    };
    interface HTMLEclLinkElement extends Components.EclLink, HTMLStencilElement {
    }
    var HTMLEclLinkElement: {
        prototype: HTMLEclLinkElement;
        new (): HTMLEclLinkElement;
    };
    interface HTMLEclMediaContainerElement extends Components.EclMediaContainer, HTMLStencilElement {
    }
    var HTMLEclMediaContainerElement: {
        prototype: HTMLEclMediaContainerElement;
        new (): HTMLEclMediaContainerElement;
    };
    interface HTMLEclMessageElement extends Components.EclMessage, HTMLStencilElement {
    }
    var HTMLEclMessageElement: {
        prototype: HTMLEclMessageElement;
        new (): HTMLEclMessageElement;
    };
    interface HTMLEclNewsTickerElement extends Components.EclNewsTicker, HTMLStencilElement {
    }
    var HTMLEclNewsTickerElement: {
        prototype: HTMLEclNewsTickerElement;
        new (): HTMLEclNewsTickerElement;
    };
    interface HTMLEclNewsTickerItemElement extends Components.EclNewsTickerItem, HTMLStencilElement {
    }
    var HTMLEclNewsTickerItemElement: {
        prototype: HTMLEclNewsTickerItemElement;
        new (): HTMLEclNewsTickerItemElement;
    };
    interface HTMLEclPageBannerElement extends Components.EclPageBanner, HTMLStencilElement {
    }
    var HTMLEclPageBannerElement: {
        prototype: HTMLEclPageBannerElement;
        new (): HTMLEclPageBannerElement;
    };
    interface HTMLEclPageHeaderElement extends Components.EclPageHeader, HTMLStencilElement {
    }
    var HTMLEclPageHeaderElement: {
        prototype: HTMLEclPageHeaderElement;
        new (): HTMLEclPageHeaderElement;
    };
    interface HTMLEclPopoverElement extends Components.EclPopover, HTMLStencilElement {
    }
    var HTMLEclPopoverElement: {
        prototype: HTMLEclPopoverElement;
        new (): HTMLEclPopoverElement;
    };
    interface HTMLEclPopoverItemElement extends Components.EclPopoverItem, HTMLStencilElement {
    }
    var HTMLEclPopoverItemElement: {
        prototype: HTMLEclPopoverItemElement;
        new (): HTMLEclPopoverItemElement;
    };
    interface HTMLEclRatingFieldElement extends Components.EclRatingField, HTMLStencilElement {
    }
    var HTMLEclRatingFieldElement: {
        prototype: HTMLEclRatingFieldElement;
        new (): HTMLEclRatingFieldElement;
    };
    interface HTMLEclRatingStarElement extends Components.EclRatingStar, HTMLStencilElement {
    }
    var HTMLEclRatingStarElement: {
        prototype: HTMLEclRatingStarElement;
        new (): HTMLEclRatingStarElement;
    };
    interface HTMLEclSearchFormElement extends Components.EclSearchForm, HTMLStencilElement {
    }
    var HTMLEclSearchFormElement: {
        prototype: HTMLEclSearchFormElement;
        new (): HTMLEclSearchFormElement;
    };
    interface HTMLEclSelectElement extends Components.EclSelect, HTMLStencilElement {
    }
    var HTMLEclSelectElement: {
        prototype: HTMLEclSelectElement;
        new (): HTMLEclSelectElement;
    };
    interface HTMLEclSiteHeaderElement extends Components.EclSiteHeader, HTMLStencilElement {
    }
    var HTMLEclSiteHeaderElement: {
        prototype: HTMLEclSiteHeaderElement;
        new (): HTMLEclSiteHeaderElement;
    };
    interface HTMLEclSocialMediaShareElement extends Components.EclSocialMediaShare, HTMLStencilElement {
    }
    var HTMLEclSocialMediaShareElement: {
        prototype: HTMLEclSocialMediaShareElement;
        new (): HTMLEclSocialMediaShareElement;
    };
    interface HTMLEclSocialMediaShareItemElement extends Components.EclSocialMediaShareItem, HTMLStencilElement {
    }
    var HTMLEclSocialMediaShareItemElement: {
        prototype: HTMLEclSocialMediaShareItemElement;
        new (): HTMLEclSocialMediaShareItemElement;
    };
    interface HTMLEclSpinnerElement extends Components.EclSpinner, HTMLStencilElement {
    }
    var HTMLEclSpinnerElement: {
        prototype: HTMLEclSpinnerElement;
        new (): HTMLEclSpinnerElement;
    };
    interface HTMLEclTagElement extends Components.EclTag, HTMLStencilElement {
    }
    var HTMLEclTagElement: {
        prototype: HTMLEclTagElement;
        new (): HTMLEclTagElement;
    };
    interface HTMLEclTextareaElement extends Components.EclTextarea, HTMLStencilElement {
    }
    var HTMLEclTextareaElement: {
        prototype: HTMLEclTextareaElement;
        new (): HTMLEclTextareaElement;
    };
    interface HTMLEclTimelineElement extends Components.EclTimeline, HTMLStencilElement {
    }
    var HTMLEclTimelineElement: {
        prototype: HTMLEclTimelineElement;
        new (): HTMLEclTimelineElement;
    };
    interface HTMLEclTimelineItemElement extends Components.EclTimelineItem, HTMLStencilElement {
    }
    var HTMLEclTimelineItemElement: {
        prototype: HTMLEclTimelineItemElement;
        new (): HTMLEclTimelineItemElement;
    };
    interface HTMLElementTagNameMap {
        "ecl-accordion": HTMLEclAccordionElement;
        "ecl-accordion-item": HTMLEclAccordionItemElement;
        "ecl-banner": HTMLEclBannerElement;
        "ecl-blockquote": HTMLEclBlockquoteElement;
        "ecl-breadcrumb": HTMLEclBreadcrumbElement;
        "ecl-breadcrumb-item": HTMLEclBreadcrumbItemElement;
        "ecl-button": HTMLEclButtonElement;
        "ecl-carousel": HTMLEclCarouselElement;
        "ecl-carousel-item": HTMLEclCarouselItemElement;
        "ecl-category-filter": HTMLEclCategoryFilterElement;
        "ecl-category-filter-item": HTMLEclCategoryFilterItemElement;
        "ecl-content-block": HTMLEclContentBlockElement;
        "ecl-date-block": HTMLEclDateBlockElement;
        "ecl-datepicker": HTMLEclDatepickerElement;
        "ecl-description-list": HTMLEclDescriptionListElement;
        "ecl-description-list-definition": HTMLEclDescriptionListDefinitionElement;
        "ecl-description-list-term": HTMLEclDescriptionListTermElement;
        "ecl-expandable": HTMLEclExpandableElement;
        "ecl-fact-figures": HTMLEclFactFiguresElement;
        "ecl-fact-figures-item": HTMLEclFactFiguresItemElement;
        "ecl-featured-item": HTMLEclFeaturedItemElement;
        "ecl-file": HTMLEclFileElement;
        "ecl-file-translations": HTMLEclFileTranslationsElement;
        "ecl-file-translations-item": HTMLEclFileTranslationsItemElement;
        "ecl-form-group": HTMLEclFormGroupElement;
        "ecl-gallery": HTMLEclGalleryElement;
        "ecl-gallery-item": HTMLEclGalleryItemElement;
        "ecl-hero-banner": HTMLEclHeroBannerElement;
        "ecl-icon": HTMLEclIconElement;
        "ecl-inpage-navigation": HTMLEclInpageNavigationElement;
        "ecl-inpage-navigation-item": HTMLEclInpageNavigationItemElement;
        "ecl-input": HTMLEclInputElement;
        "ecl-label": HTMLEclLabelElement;
        "ecl-language-item": HTMLEclLanguageItemElement;
        "ecl-link": HTMLEclLinkElement;
        "ecl-media-container": HTMLEclMediaContainerElement;
        "ecl-message": HTMLEclMessageElement;
        "ecl-news-ticker": HTMLEclNewsTickerElement;
        "ecl-news-ticker-item": HTMLEclNewsTickerItemElement;
        "ecl-page-banner": HTMLEclPageBannerElement;
        "ecl-page-header": HTMLEclPageHeaderElement;
        "ecl-popover": HTMLEclPopoverElement;
        "ecl-popover-item": HTMLEclPopoverItemElement;
        "ecl-rating-field": HTMLEclRatingFieldElement;
        "ecl-rating-star": HTMLEclRatingStarElement;
        "ecl-search-form": HTMLEclSearchFormElement;
        "ecl-select": HTMLEclSelectElement;
        "ecl-site-header": HTMLEclSiteHeaderElement;
        "ecl-social-media-share": HTMLEclSocialMediaShareElement;
        "ecl-social-media-share-item": HTMLEclSocialMediaShareItemElement;
        "ecl-spinner": HTMLEclSpinnerElement;
        "ecl-tag": HTMLEclTagElement;
        "ecl-textarea": HTMLEclTextareaElement;
        "ecl-timeline": HTMLEclTimelineElement;
        "ecl-timeline-item": HTMLEclTimelineItemElement;
    }
}
declare namespace LocalJSX {
    interface EclAccordion {
        "eclScript"?: boolean;
        "styleClass"?: string;
        "theme"?: string;
        "withUtils"?: boolean;
    }
    interface EclAccordionItem {
        "expanded"?: boolean;
        "label"?: string;
        "styleClass"?: string;
        "theme"?: string;
    }
    interface EclBanner {
        "bannerTitle"?: string;
        "centered"?: boolean;
        "credit"?: string;
        "ctaLabel"?: string;
        "ctaLink"?: string;
        "external"?: boolean;
        "fullWidth"?: boolean;
        "image"?: string;
        "size"?: string;
        "styleClass"?: string;
        "theme"?: string;
        "variant"?: string;
    }
    interface EclBlockquote {
        "author"?: string;
        "image"?: string;
        "imageAlt"?: string;
        "styleClass"?: string;
        "theme"?: string;
    }
    interface EclBreadcrumb {
        "eclScript"?: boolean;
        "minItemsRight"?: number;
        "styleClass"?: string;
        "theme"?: string;
        "variant"?: string;
    }
    interface EclBreadcrumbItem {
        "buttonAriaLabel"?: string;
        "currentPage"?: boolean;
        "ellipsis"?: boolean;
        "path"?: string;
        "styleClass"?: string;
        "theme"?: string;
        "variant"?: string;
    }
    interface EclButton {
        "styleClass"?: string;
        "theme"?: string;
        "type"?: string;
        "variant"?: string;
    }
    interface EclCarousel {
        "carouselId"?: string;
        "counterLabel"?: string;
        "eclScript"?: boolean;
        "slidesNumber"?: number;
        "srNavigation"?: string;
        "srNext"?: string;
        "srPause"?: string;
        "srPlay"?: string;
        "srPrevious"?: string;
        "styleClass"?: string;
        "theme"?: string;
    }
    interface EclCarouselItem {
        "ariaLabel"?: string;
        "bannerTitle"?: string;
        "bannerVariant"?: string;
        "centered"?: boolean;
        "ctaLabel"?: string;
        "ctaLink"?: string;
        "image"?: string;
        "size"?: string;
        "styleClass"?: string;
        "theme"?: string;
    }
    interface EclCategoryFilter {
        "eclScript"?: boolean;
        "styleClass"?: string;
        "theme"?: string;
    }
    interface EclCategoryFilterItem {
        "label"?: string;
        "level"?: number;
        "path"?: string;
        "styleClass"?: string;
        "subItems"?: boolean;
        "theme"?: string;
    }
    interface EclContentBlock {
        "hasDescription"?: boolean;
        "hasLabels"?: boolean;
        "hasLinks"?: boolean;
        "hasLists"?: boolean;
        "hasSecondaryLinks"?: boolean;
        "hasTitle"?: boolean;
        "metaPrimary"?: string;
        "metaSecondary"?: string;
        "styleClass"?: string;
        "theme"?: string;
    }
    interface EclDateBlock {
        "dateTime"?: string;
        "day"?: string;
        "month"?: string;
        "monthFull"?: string;
        "styleClass"?: string;
        "theme"?: string;
        "variant"?: string;
        "year"?: string;
    }
    interface EclDatepicker {
        "defaultValue"?: string;
        "disabled"?: boolean;
        "inputId"?: string;
        "invalid"?: boolean;
        "name"?: string;
        "placeholder"?: string;
        "required"?: boolean;
        "styleClass"?: string;
        "theme"?: string;
        "type"?: string;
    }
    interface EclDescriptionList {
        "styleClass"?: string;
        "theme"?: string;
        "variant"?: string;
    }
    interface EclDescriptionListDefinition {
        "items"?: string;
        "styleClass"?: string;
        "theme"?: string;
        "type"?: string;
    }
    interface EclDescriptionListTerm {
        "styleClass"?: string;
        "theme"?: string;
    }
    interface EclExpandable {
        "eclScript"?: boolean;
        "isExpanded"?: boolean;
        "labelCollapsed"?: string;
        "labelExpanded"?: string;
        "styleClass"?: string;
        "theme"?: string;
        "withUtils"?: boolean;
    }
    interface EclFactFigures {
        "columns"?: number;
        "displayIcons"?: boolean;
        "styleClass"?: string;
        "theme"?: string;
        "withUtils"?: boolean;
    }
    interface EclFactFiguresItem {
        "icon"?: string;
        "iconTransform"?: string;
        "itemTitle"?: string;
        "styleClass"?: string;
        "theme"?: string;
        "value"?: string;
    }
    interface EclFeaturedItem {
        "defaultContainerClass"?: string;
        "eclScript"?: boolean;
        "image"?: string;
        "itemTitle"?: string;
        "mediaCaption"?: string;
        "position"?: string;
        "styleClass"?: string;
        "theme"?: string;
        "variant"?: string;
        "withUtils"?: boolean;
    }
    interface EclFile {
        "ariaLabel"?: string;
        "detailMeta"?: string;
        "downloadLabel"?: string;
        "downloadLink"?: string;
        "eclScript"?: boolean;
        "fileTitle"?: string;
        "image"?: string;
        "imageAlt"?: string;
        "labels"?: string;
        "language"?: string;
        "meta"?: string;
        "styleClass"?: string;
        "taxonomies"?: string;
        "taxonomiesLabel"?: string;
        "theme"?: string;
        "variant"?: string;
    }
    interface EclFileTranslations {
        "others"?: boolean;
        "styleClass"?: string;
        "theme"?: string;
        "toggleLabel"?: string;
    }
    interface EclFileTranslationsItem {
        "downloadLabel"?: string;
        "downloadLink"?: string;
        "fileTitle"?: string;
        "language"?: string;
        "meta"?: string;
        "styleClass"?: string;
        "theme"?: string;
        "variant"?: string;
    }
    interface EclFormGroup {
        "helperId"?: string;
        "helperText"?: string;
        "invalid"?: boolean;
        "invalidIcon"?: string;
        "invalidText"?: string;
        "label"?: string;
        "labelClass"?: string;
        "name"?: string;
        "optionalText"?: string;
        "required"?: boolean;
        "requiredText"?: string;
        "styleClass"?: string;
        "theme"?: string;
    }
    interface EclGallery {
        "closeLabel"?: string;
        "counterLabel"?: string;
        "counterSeparator"?: string;
        "description"?: string;
        "downloadLabel"?: string;
        "eclScript"?: boolean;
        "footerLinkLabel"?: string;
        "footerLinkPath"?: string;
        "meta"?: string;
        "nextLabel"?: string;
        "prevLabel"?: string;
        "shareLabel"?: string;
        "slidesNumber"?: number;
        "styleClass"?: string;
        "theme"?: string;
        "viewAllLabel"?: string;
    }
    interface EclGalleryItem {
        "icon"?: string;
        "imageAlt"?: string;
        "mediaHref"?: string;
        "mediaIframeHref"?: string;
        "mediaSharePath"?: string;
        "meta"?: string;
        "styleClass"?: string;
        "theme"?: string;
        "type"?: string;
    }
    interface EclHeroBanner {
        "bannerTitle"?: string;
        "centered"?: boolean;
        "credit"?: string;
        "ctaLabel"?: string;
        "ctaLink"?: string;
        "external"?: boolean;
        "fullWidth"?: boolean;
        "image"?: string;
        "styleClass"?: string;
        "theme"?: string;
        "variant"?: string;
    }
    interface EclIcon {
        "color"?: string;
        "icon"?: string;
        "path"?: string;
        "size"?: string;
        "sprite"?: string;
        "styleClass"?: string;
        "theme"?: string;
        "transform"?: string;
    }
    interface EclInpageNavigation {
        "eclScript"?: boolean;
        "inpageId"?: string;
        "inpageTitle"?: string;
        "styleClass"?: string;
        "theme"?: string;
        "withUtils"?: boolean;
    }
    interface EclInpageNavigationItem {
        "path"?: string;
        "styleClass"?: string;
        "theme"?: string;
    }
    interface EclInput {
        "buttonChooseLabel"?: string;
        "buttonReplaceLabel"?: string;
        "defaultValue"?: string;
        "disabled"?: boolean;
        "eclScript"?: boolean;
        "helperId"?: string;
        "helperText"?: string;
        "inputClass"?: string;
        "inputId"?: string;
        "invalid"?: boolean;
        "label"?: string;
        "max"?: number;
        "min"?: number;
        "multiple"?: boolean;
        "name"?: string;
        "placeholder"?: string;
        "required"?: boolean;
        "step"?: number;
        "styleClass"?: string;
        "theme"?: string;
        "type"?: string;
        "valueLabel"?: string;
        "width"?: string;
        "withUtils"?: boolean;
    }
    interface EclLabel {
        "styleClass"?: string;
        "theme"?: string;
        "variant"?: string;
    }
    interface EclLanguageItem {
        "active"?: boolean;
        "langCode"?: string;
        "language"?: string;
        "path"?: string;
        "styleClass"?: string;
        "theme"?: string;
    }
    interface EclLink {
        "external"?: boolean;
        "name"?: string;
        "path"?: string;
        "styleClass"?: string;
        "theme"?: string;
        "titleAttr"?: string;
        "variant"?: string;
    }
    interface EclMediaContainer {
        "alt"?: string;
        "description"?: string;
        "eclScript"?: boolean;
        "embeddedMedia"?: boolean;
        "fullWidth"?: boolean;
        "image"?: string;
        "ratio"?: string;
        "sources"?: string;
        "styleClass"?: string;
        "theme"?: string;
        "tracks"?: string;
        "withUtils"?: boolean;
    }
    interface EclMessage {
        "closeLabel"?: string;
        "eclScript"?: boolean;
        "messageTitle"?: string;
        "styleClass"?: string;
        "theme"?: string;
        "variant"?: string;
    }
    interface EclNewsTicker {
        "counterLabel"?: string;
        "eclScript"?: boolean;
        "srNext"?: string;
        "srPause"?: string;
        "srPrev"?: string;
        "styleClass"?: string;
        "theme"?: string;
    }
    interface EclNewsTickerItem {
        "path"?: string;
        "styleClass"?: string;
        "theme"?: string;
    }
    interface EclPageBanner {
        "bannerTitle"?: string;
        "centered"?: boolean;
        "credit"?: string;
        "ctaLabel"?: string;
        "ctaLink"?: string;
        "external"?: boolean;
        "fullWidth"?: boolean;
        "image"?: string;
        "styleClass"?: string;
        "theme"?: string;
        "variant"?: string;
    }
    interface EclPageHeader {
        "headerTitle"?: string;
        "image"?: string;
        "meta"?: string;
        "overlay"?: string;
        "styleClass"?: string;
        "theme"?: string;
        "thumbnail"?: string;
        "thumbnailAlt"?: string;
        "variant"?: string;
    }
    interface EclPopover {
        "eclScript"?: boolean;
        "icon"?: string;
        "iconSize"?: string;
        "iconSprite"?: string;
        "itemId"?: string;
        "list"?: boolean;
        "styleClass"?: string;
        "theme"?: string;
        "toggleLabel"?: string;
    }
    interface EclPopoverItem {
        "icon"?: string;
        "iconSize"?: string;
        "iconSprite"?: string;
        "path"?: string;
        "styleClass"?: string;
        "theme"?: string;
    }
    interface EclRatingField {
        "disabled"?: boolean;
        "required"?: boolean;
        "styleClass"?: string;
        "theme"?: string;
    }
    interface EclRatingStar {
        "checked"?: boolean;
        "disabled"?: boolean;
        "icon"?: string;
        "iconFilled"?: string;
        "itemId"?: string;
        "label"?: string;
        "name"?: string;
        "required"?: boolean;
        "styleClass"?: string;
        "theme"?: string;
        "value"?: string;
    }
    interface EclSearchForm {
        "buttonAriaLabel"?: string;
        "buttonLabel"?: string;
        "disabled"?: boolean;
        "helperId"?: string;
        "helperText"?: string;
        "inputId"?: string;
        "invalid"?: boolean;
        "invalidText"?: string;
        "label"?: string;
        "name"?: string;
        "placeholder"?: string;
        "required"?: boolean;
        "styleClass"?: string;
        "theme"?: string;
        "type"?: string;
        "width"?: string;
    }
    interface EclSelect {
        "disabled"?: boolean;
        "eclScript"?: boolean;
        "invalid"?: boolean;
        "multiple"?: boolean;
        "multipleAllText"?: string;
        "multipleClearAllText"?: string;
        "multipleCloseText"?: string;
        "multiplePlaceholder"?: string;
        "multipleSearchNoResultsText"?: string;
        "multipleSearchText"?: string;
        "name"?: string;
        "required"?: boolean;
        "selectId"?: string;
        "styleClass"?: string;
        "theme"?: string;
        "width"?: string;
    }
    interface EclSiteHeader {
        "closeLabel"?: string;
        "eclScript"?: boolean;
        "euLabel"?: string;
        "langCode"?: string;
        "language"?: string;
        "languageAriaLabel"?: string;
        "languageBlock"?: boolean;
        "languageId"?: string;
        "languageTitle"?: string;
        "loginBlock"?: boolean;
        "loginLink"?: string;
        "loginText"?: string;
        "logoAlt"?: string;
        "logoTitle"?: string;
        "nonEuLabel"?: string;
        "searchBlock"?: boolean;
        "searchPlaceholder"?: string;
        "searchText"?: string;
        "styleClass"?: string;
        "theme"?: string;
    }
    interface EclSocialMediaShare {
        "description"?: string;
        "styleClass"?: string;
        "theme"?: string;
        "variant"?: string;
    }
    interface EclSocialMediaShareItem {
        "icon"?: string;
        "sharePath"?: string;
        "styleClass"?: string;
        "theme"?: string;
    }
    interface EclSpinner {
        "centered"?: boolean;
        "overlay"?: boolean;
        "size"?: string;
        "styleClass"?: string;
        "theme"?: string;
        "variant"?: string;
        "visible"?: boolean;
    }
    interface EclTag {
        "external"?: boolean;
        "styleClass"?: string;
        "theme"?: string;
        "variant"?: string;
    }
    interface EclTextarea {
        "disabled"?: boolean;
        "invalid"?: boolean;
        "name"?: string;
        "placeholder"?: string;
        "required"?: boolean;
        "rows"?: number;
        "styleClass"?: string;
        "textareaId"?: string;
        "theme"?: string;
        "width"?: string;
    }
    interface EclTimeline {
        "eclScript"?: boolean;
        "styleClass"?: string;
        "theme"?: string;
    }
    interface EclTimelineItem {
        "itemTitle"?: string;
        "label"?: string;
        "styleClass"?: string;
        "theme"?: string;
        "type"?: string;
    }
    interface IntrinsicElements {
        "ecl-accordion": EclAccordion;
        "ecl-accordion-item": EclAccordionItem;
        "ecl-banner": EclBanner;
        "ecl-blockquote": EclBlockquote;
        "ecl-breadcrumb": EclBreadcrumb;
        "ecl-breadcrumb-item": EclBreadcrumbItem;
        "ecl-button": EclButton;
        "ecl-carousel": EclCarousel;
        "ecl-carousel-item": EclCarouselItem;
        "ecl-category-filter": EclCategoryFilter;
        "ecl-category-filter-item": EclCategoryFilterItem;
        "ecl-content-block": EclContentBlock;
        "ecl-date-block": EclDateBlock;
        "ecl-datepicker": EclDatepicker;
        "ecl-description-list": EclDescriptionList;
        "ecl-description-list-definition": EclDescriptionListDefinition;
        "ecl-description-list-term": EclDescriptionListTerm;
        "ecl-expandable": EclExpandable;
        "ecl-fact-figures": EclFactFigures;
        "ecl-fact-figures-item": EclFactFiguresItem;
        "ecl-featured-item": EclFeaturedItem;
        "ecl-file": EclFile;
        "ecl-file-translations": EclFileTranslations;
        "ecl-file-translations-item": EclFileTranslationsItem;
        "ecl-form-group": EclFormGroup;
        "ecl-gallery": EclGallery;
        "ecl-gallery-item": EclGalleryItem;
        "ecl-hero-banner": EclHeroBanner;
        "ecl-icon": EclIcon;
        "ecl-inpage-navigation": EclInpageNavigation;
        "ecl-inpage-navigation-item": EclInpageNavigationItem;
        "ecl-input": EclInput;
        "ecl-label": EclLabel;
        "ecl-language-item": EclLanguageItem;
        "ecl-link": EclLink;
        "ecl-media-container": EclMediaContainer;
        "ecl-message": EclMessage;
        "ecl-news-ticker": EclNewsTicker;
        "ecl-news-ticker-item": EclNewsTickerItem;
        "ecl-page-banner": EclPageBanner;
        "ecl-page-header": EclPageHeader;
        "ecl-popover": EclPopover;
        "ecl-popover-item": EclPopoverItem;
        "ecl-rating-field": EclRatingField;
        "ecl-rating-star": EclRatingStar;
        "ecl-search-form": EclSearchForm;
        "ecl-select": EclSelect;
        "ecl-site-header": EclSiteHeader;
        "ecl-social-media-share": EclSocialMediaShare;
        "ecl-social-media-share-item": EclSocialMediaShareItem;
        "ecl-spinner": EclSpinner;
        "ecl-tag": EclTag;
        "ecl-textarea": EclTextarea;
        "ecl-timeline": EclTimeline;
        "ecl-timeline-item": EclTimelineItem;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ecl-accordion": LocalJSX.EclAccordion & JSXBase.HTMLAttributes<HTMLEclAccordionElement>;
            "ecl-accordion-item": LocalJSX.EclAccordionItem & JSXBase.HTMLAttributes<HTMLEclAccordionItemElement>;
            "ecl-banner": LocalJSX.EclBanner & JSXBase.HTMLAttributes<HTMLEclBannerElement>;
            "ecl-blockquote": LocalJSX.EclBlockquote & JSXBase.HTMLAttributes<HTMLEclBlockquoteElement>;
            "ecl-breadcrumb": LocalJSX.EclBreadcrumb & JSXBase.HTMLAttributes<HTMLEclBreadcrumbElement>;
            "ecl-breadcrumb-item": LocalJSX.EclBreadcrumbItem & JSXBase.HTMLAttributes<HTMLEclBreadcrumbItemElement>;
            "ecl-button": LocalJSX.EclButton & JSXBase.HTMLAttributes<HTMLEclButtonElement>;
            "ecl-carousel": LocalJSX.EclCarousel & JSXBase.HTMLAttributes<HTMLEclCarouselElement>;
            "ecl-carousel-item": LocalJSX.EclCarouselItem & JSXBase.HTMLAttributes<HTMLEclCarouselItemElement>;
            "ecl-category-filter": LocalJSX.EclCategoryFilter & JSXBase.HTMLAttributes<HTMLEclCategoryFilterElement>;
            "ecl-category-filter-item": LocalJSX.EclCategoryFilterItem & JSXBase.HTMLAttributes<HTMLEclCategoryFilterItemElement>;
            "ecl-content-block": LocalJSX.EclContentBlock & JSXBase.HTMLAttributes<HTMLEclContentBlockElement>;
            "ecl-date-block": LocalJSX.EclDateBlock & JSXBase.HTMLAttributes<HTMLEclDateBlockElement>;
            "ecl-datepicker": LocalJSX.EclDatepicker & JSXBase.HTMLAttributes<HTMLEclDatepickerElement>;
            "ecl-description-list": LocalJSX.EclDescriptionList & JSXBase.HTMLAttributes<HTMLEclDescriptionListElement>;
            "ecl-description-list-definition": LocalJSX.EclDescriptionListDefinition & JSXBase.HTMLAttributes<HTMLEclDescriptionListDefinitionElement>;
            "ecl-description-list-term": LocalJSX.EclDescriptionListTerm & JSXBase.HTMLAttributes<HTMLEclDescriptionListTermElement>;
            "ecl-expandable": LocalJSX.EclExpandable & JSXBase.HTMLAttributes<HTMLEclExpandableElement>;
            "ecl-fact-figures": LocalJSX.EclFactFigures & JSXBase.HTMLAttributes<HTMLEclFactFiguresElement>;
            "ecl-fact-figures-item": LocalJSX.EclFactFiguresItem & JSXBase.HTMLAttributes<HTMLEclFactFiguresItemElement>;
            "ecl-featured-item": LocalJSX.EclFeaturedItem & JSXBase.HTMLAttributes<HTMLEclFeaturedItemElement>;
            "ecl-file": LocalJSX.EclFile & JSXBase.HTMLAttributes<HTMLEclFileElement>;
            "ecl-file-translations": LocalJSX.EclFileTranslations & JSXBase.HTMLAttributes<HTMLEclFileTranslationsElement>;
            "ecl-file-translations-item": LocalJSX.EclFileTranslationsItem & JSXBase.HTMLAttributes<HTMLEclFileTranslationsItemElement>;
            "ecl-form-group": LocalJSX.EclFormGroup & JSXBase.HTMLAttributes<HTMLEclFormGroupElement>;
            "ecl-gallery": LocalJSX.EclGallery & JSXBase.HTMLAttributes<HTMLEclGalleryElement>;
            "ecl-gallery-item": LocalJSX.EclGalleryItem & JSXBase.HTMLAttributes<HTMLEclGalleryItemElement>;
            "ecl-hero-banner": LocalJSX.EclHeroBanner & JSXBase.HTMLAttributes<HTMLEclHeroBannerElement>;
            "ecl-icon": LocalJSX.EclIcon & JSXBase.HTMLAttributes<HTMLEclIconElement>;
            "ecl-inpage-navigation": LocalJSX.EclInpageNavigation & JSXBase.HTMLAttributes<HTMLEclInpageNavigationElement>;
            "ecl-inpage-navigation-item": LocalJSX.EclInpageNavigationItem & JSXBase.HTMLAttributes<HTMLEclInpageNavigationItemElement>;
            "ecl-input": LocalJSX.EclInput & JSXBase.HTMLAttributes<HTMLEclInputElement>;
            "ecl-label": LocalJSX.EclLabel & JSXBase.HTMLAttributes<HTMLEclLabelElement>;
            "ecl-language-item": LocalJSX.EclLanguageItem & JSXBase.HTMLAttributes<HTMLEclLanguageItemElement>;
            "ecl-link": LocalJSX.EclLink & JSXBase.HTMLAttributes<HTMLEclLinkElement>;
            "ecl-media-container": LocalJSX.EclMediaContainer & JSXBase.HTMLAttributes<HTMLEclMediaContainerElement>;
            "ecl-message": LocalJSX.EclMessage & JSXBase.HTMLAttributes<HTMLEclMessageElement>;
            "ecl-news-ticker": LocalJSX.EclNewsTicker & JSXBase.HTMLAttributes<HTMLEclNewsTickerElement>;
            "ecl-news-ticker-item": LocalJSX.EclNewsTickerItem & JSXBase.HTMLAttributes<HTMLEclNewsTickerItemElement>;
            "ecl-page-banner": LocalJSX.EclPageBanner & JSXBase.HTMLAttributes<HTMLEclPageBannerElement>;
            "ecl-page-header": LocalJSX.EclPageHeader & JSXBase.HTMLAttributes<HTMLEclPageHeaderElement>;
            "ecl-popover": LocalJSX.EclPopover & JSXBase.HTMLAttributes<HTMLEclPopoverElement>;
            "ecl-popover-item": LocalJSX.EclPopoverItem & JSXBase.HTMLAttributes<HTMLEclPopoverItemElement>;
            "ecl-rating-field": LocalJSX.EclRatingField & JSXBase.HTMLAttributes<HTMLEclRatingFieldElement>;
            "ecl-rating-star": LocalJSX.EclRatingStar & JSXBase.HTMLAttributes<HTMLEclRatingStarElement>;
            "ecl-search-form": LocalJSX.EclSearchForm & JSXBase.HTMLAttributes<HTMLEclSearchFormElement>;
            "ecl-select": LocalJSX.EclSelect & JSXBase.HTMLAttributes<HTMLEclSelectElement>;
            "ecl-site-header": LocalJSX.EclSiteHeader & JSXBase.HTMLAttributes<HTMLEclSiteHeaderElement>;
            "ecl-social-media-share": LocalJSX.EclSocialMediaShare & JSXBase.HTMLAttributes<HTMLEclSocialMediaShareElement>;
            "ecl-social-media-share-item": LocalJSX.EclSocialMediaShareItem & JSXBase.HTMLAttributes<HTMLEclSocialMediaShareItemElement>;
            "ecl-spinner": LocalJSX.EclSpinner & JSXBase.HTMLAttributes<HTMLEclSpinnerElement>;
            "ecl-tag": LocalJSX.EclTag & JSXBase.HTMLAttributes<HTMLEclTagElement>;
            "ecl-textarea": LocalJSX.EclTextarea & JSXBase.HTMLAttributes<HTMLEclTextareaElement>;
            "ecl-timeline": LocalJSX.EclTimeline & JSXBase.HTMLAttributes<HTMLEclTimelineElement>;
            "ecl-timeline-item": LocalJSX.EclTimelineItem & JSXBase.HTMLAttributes<HTMLEclTimelineItemElement>;
        }
    }
}
